### ISSUE TITLE
it eats my RAM

### ISSUE THREAD

**Issue by nh2** [hspec/hspec#169]
I just wrote something similar to

``` haskell
import Test.Hspec
import Control.Monad
import Data.Word

main :: IO ()
main = hspec $ describe "tests" $ do

    it "exhaustive testing for Word32" $ do
      forM_ [0..maxBound::Word32] $ \w ->
        w `shouldBe` w
```

And it started eating all my RAM.

Why is that? Does hspec need to track all assertions, could it not discard not-failing ones?

**Comment by sol** [comment]
There is an upcoming feature that requires to run the spec twice (see https://github.com/hspec/hspec/issues/291). At this point we will have sharing, so the whole spec tree will be constructed in memory. So it won't run in constant space anymore. This is even the case when you don't use that feature.

@nh2 dost this have any practical implications for you?

**Comment by nh2** [comment]
@sol yes, depending on what you mean, I guess it would break my test (or any machine that runs it).

The key question is what the scope of `--rerun` in #291 is. Do you want to keep track of all `it`s or all `Assertion`s (all `shouldBe`s)?

If it's all `it`s, I guess that's reasonable, and my test has only one of those.

**Comment by sol** [comment]
All `it`s.

Anyway, I managed to retain the constant space behavior when `--rerun-all` is not a used.

Closing.
