### ISSUE TITLE
Run with detailed, colored output?

### ISSUE THREAD

**Issue by adnelson** [hspec/hspec#184]
I'm just getting started with HSpec. My cabal file has the following for the test suite:

``` cabal
Test-Suite spec
  Type:                 exitcode-stdio-1.0
  Default-Language:     Haskell2010
  Hs-Source-Dirs:       src
                      , test
  Main-Is:              Spec.hs
  Build-Depends:        base >=4.7 && <4.8, containers >=0.5 && <0.6, unordered-contain\
ers, lens, text, aeson, random, mtl, transformers, parsec, oneormore, hspec
```

My tests run OK, but when they run all I see is:

```
$ cabal test
Building foo-0.0.0.1...
Preprocessing executable 'foo' for foo-0.0.0.1...
Preprocessing test suite 'spec' for foo-0.0.0.1...
Running 1 test suites...
Test suite spec: RUNNING...
Test suite spec: PASS
Test suite logged to: dist/test/foo-0.0.0.1-spec.log
1 of 1 test suites (1 of 1 test cases) passed.
```

So as you can see, it doesn't show the individual tests running (the `it`s or `describe`s). Also you can't see it but there's no color in the output.

What can I do to get a detailed output, with colors, as shown in the docs?

**Comment by jhrcek** [comment]
For anyone coming to this later, here's what you can do with cabal 3.4:

```bash
cabal test --test-show-details=streaming --test-option=--color
```

or alternatively
```bash
# save the flags to your cabal.project.local
cabal configure --enable-tests --test-show-details=streaming --test-option=--color

# run tests with configuration above
cabal test
```

**Comment by NiekPas** [comment]
> ```shell
> ```shell
> cabal test --test-show-details=streaming --test-option=--color
> ```
> 
> 
>     
>       
>     
> 
>       
>     
> 
>     
>   
> ```

This doesn't work for me; it outputs the following: `The option `--color` expects an argument.`

**Comment by expipiplus1** [comment]
To avoid going through cabal altogether I use `$(cabal build test >&2 && cabal list-bin test) --my --test options`

**Comment by sol** [comment]
@expipiplus1 I think we want to add this to the documentation https://github.com/hspec/hspec/issues/836.

**Comment by niekvandepas** [comment]
> For anyone coming to this later, here's what you can do with cabal 3.4:
> 
> ```shell
> cabal test --test-show-details=streaming --test-option=--color
> ```
> 
> or alternatively
> 
> ```shell
> # save the flags to your cabal.project.local
> cabal configure --enable-tests --test-show-details=streaming --test-option=--color
> 
> # run tests with configuration above
> cabal test
> ```

@jhrcek  This doesn't seem to work in Cabal 3.10:

```
cabal test --test-show-details=streaming --test-option=--color
```

```
Test suite markdown-parser-test: RUNNING...
The option `--color` expects an argument.

Usage: markdown-parser-test [(-p|--pattern PATTERN)] [-t|--timeout DURATION]
                            [--hide-progress] [-l|--list-tests]
                            [-j|--num-threads NUMBER] [-q|--quiet]
                            [--hide-successes]
                            [--min-duration-to-report DURATION]
                            [--color never|always|auto] [--ansi-tricks ARG]
Test suite markdown-parser-test: FAIL
```

**Comment by sol** [comment]
@niekvandepas your comment is not related to Hspec and potentially misleading for Hspec users  that come here in the future. For that reason, I'm going to delete that comment.
