### ISSUE TITLE
Improve location heuristic

### ISSUE THREAD

**Issue by sol** [hspec/hspec#207]
Currently, the number of occurrences of a specific description in the source file and the spec tree have to match exactly.  Otherwise, no location information is added for the corresponding spec items.

In the case when a description occurs in the source file exactly once, but in the spec tree multiple times, we still may want to add source locations.

Here is an example where this would be desirable:

```haskell
import Test.Hspec
import Data.Foldable

main :: IO ()
main = hspec spec

spec :: Spec
spec = do
  forM_ [0..10] $ \n -> do
    it "is five" $ do
      n `shouldBe` 5
```

**Comment by soenkehahn** [comment]
Closing because we have proper source locations with `ghc-7.10.2` now.
