### ISSUE TITLE
Can I perform a 'before' and 'after' action with passing results

### ISSUE THREAD

**Issue by KasperJanssens** [hspec/hspec#220]
More of a question than an issue,  but I can't mark it as a question.
I would like to create a tmp folder to drop my results in, pass this tmp folder with a certain unique name (System.Posix.Temp.mkdTemp function) to my test spec and delete that folder again afterwards. I would like to achieve this by creating the tmp folder in the before action, deleting it in the after and using it in the describe. However, I don't see how to pass the result of the 'before' action to the test or to the 'after' action. Am I not looking correctly or is it indeed the objective to wrap two 'runIO' actions around the describe?

**Comment by sol** [comment]
I hope this gives the idea:

```haskell
module Spec (main, spec) where

import           Test.Hspec
           
main :: IO ()
main = hspec spec

spec :: Spec
spec = do
  before (return "foo") $ do
    after (print . ("after: " ++)) $ do
      it "example" $ \n -> do
        print n
```
There is also `beforeAll`/`afterAll`.

PRs to docs welcome ;)
