### ISSUE TITLE
How do I tell HSpec where to look for the source files to be tested

### ISSUE THREAD

**Issue by tsujigiri** [hspec/hspec#223]
I keep my source files in my project's `src` directory, the tests go to `test`. I copy the first example from the HSpec User Manual to `test/Spec.hs`. I run `runhaskell test/Spec.hs` and it works. I add `import X` to that file to import the module I actually want to test, I get load errors.

How do I tell HSpec where it should look for source files?

I'm a new to Haskell, so please bear with me if this is a trivial question. I swear I tried the Googles first.

**Comment by sol** [comment]
Ad -isrc -itest on the command line

**Comment by tsujigiri** [comment]
It works! Thank you! Might be helpful to have this in the "How to run HSpec" section of the User Manual. You know, for noobs. Like me.
