### ISSUE TITLE
Why are test failures not printed to stderr?

### ISSUE THREAD

**Issue by nh2** [hspec/hspec#224]
Hey,

@chrisdone and I got surprised today that hspec prints failed tests to stdout instead of stderr.

Is that on purpose?

In most cases I believe it is a common assumption that when a program fails with an exit code, stderr will give some hints about why that is, but with `hspec` that doesn't currently work.

Would it make sense to switch failed tests over to stderr?

**Comment by sol** [comment]
Hmm, that is a good question, not sure how that would fit in with Hspec's formatted support (which I wouldn't mind to overhaul).

I would probably look what other testinng frameworks do here.

Heads up, I'm away from any computer for 3 more weeks.

**Comment by sol** [comment]
@nh2 Have you done anything on this one?  I quickly checked rspec, which seems to write everything to `stdout`.

@soenkehahn Do you have any input on this one?

**Comment by soenkehahn** [comment]
I checked `ghc` (puts errors to `stderr`), `hlint` (puts suggestions to `stdout` while throwing a non-zero exit-code) and `pylint` (same as `hlint`). So there doesn't seem to be a a strong convention on writing to `stderr` when exiting with a non-zero exit-code.

But I don't see any real downside to switching to `stderr`, so I'd be in favor of switching.

**Comment by sol** [comment]
Would that mean that we start fragmenting output between `stdout` and `stderr` then?  Which parts exactly would we want to go to `stderr`?

**Comment by soenkehahn** [comment]
I assumed that everything would go to `stderr`. I think that's ok even in the case of success (and a zero exit-code). Is there a good reason not to do that?

**Comment by sol** [comment]
I'm not that opinionated here. If there is a strong case for switching it over to `stderr` altogether, then I'd be ok with that. I would still consider to switch the handle to `LineBuffering`, as by default print to `stderr` is incredibly slow.

Anybody still up for investigating what other testing libraries do here (`tasty`, `test-framework`)?

**Comment by chrisdone** [comment]
> as by default printing to stderr is incredibly slow.

Specifically, unbuffered by default.

**Comment by nh2** [comment]
> I assumed that everything would go to stderr. I think that's ok even in the case of success (and a zero exit-code). Is there a good reason not to do that?

My intuition says that progress reporting and output that indicates no error should go to `stdout`, while test failures go to `stderr`. If there are no failures, `stderr` would be empty.

For example, for this `hspec` output:

```
% runghc Spec.hs
                   
Prelude.head
  returns the first element of a list FAILED [1]
  returns the first element of an *arbitrary* list
  throws an exception if used with an empty list

Failures:

  1) Prelude.head returns the first element of a list
       expected: 24
        but got: 23

Randomized with seed 368995618

Finished in 0.0059 seconds
3 examples, 1 failure
```

I wouldn't be surprised if

```
Prelude.head
  returns the first element of a list FAILED [1]
  returns the first element of an *arbitrary* list
  throws an exception if used with an empty list
```

is counted as progress reporting and goes to `stdout`, and 

```
Failures:

  1) Prelude.head returns the first element of a list
       expected: 24
        but got: 23

Randomized with seed 368995618
```

is error reporting and goes to `stderr`.

**Comment by sol** [comment]
Before doing anything here I would want to know what other testing libraries for Ruby, Python, Java and Haskell do here.  My impression is that most libraries write to `stdout`, but I may be wrong here.

In addition, do we have a relevant use case where this changes is beneficial?

This is a breaking change.  I'm not opposed to breaking changes if they are beneficial for the user.  But if there is no strong case for the change, we will stay with the existing behavior.

**Comment by sol** [comment]
Nothing has happened here for over a year.

If anybody still has an interest in this, please open a new issue and address the questions from my previous comment.

Specifically:

- How do other testing libraries handle this?
- Do we have a relevant use case where this change is beneficial?
