### ISSUE TITLE
Does hspec-discover accept optional modules?

### ISSUE THREAD

**Issue by mf59816** [hspec/hspec#225]
We are about to remove hspec-discover from our project because we have tests we want to make optional (webdriver and selenium grid is just too big and disruptive to make it a mandatory test suite dependency).  This is the patch: liqd/thentos@cebd575.

Is there a way to disable individual modules handled by hspec-discover by default and activate them at build time or run time?

If not, is anybody else missing this feature?

Note: We are aware of the option of using CPP and a cabal flag, but CPP has its own disadvantages.

thanks,
m.

**Comment by mf59816** [comment]
Another simple solution would be to have one directory handled by hspec-discover, and one for the deactivateable modules.  Then at least we would have to collect only the latter by hand.

Still: something built into hspec, like a newtype wrapper around `Spec` that makes the test suite honor command line flags automaticlly would be nicer.  (-:

**Comment by sol** [comment]
Mathias, are you aware of the `-m` command-line option?

**Comment by mf59816** [comment]
Hi Simon, I am now.  Thanks!  (-:

But still not perfect: I can say something like:

    cabal test --test-option=--match --test-option=This.Module

But not:

    cabal test --test-option=--match --test-option=^selenium

Or does the pattern language support negation?

**Comment by mf59816** [comment]
Found it:

    cabal test --test-option=--skip --test-option=selenium

Problem solved.  Thanks!
