### ISSUE TITLE
generate some "it" using a forM ?

### ISSUE THREAD

**Issue by fotanus** [hspec/hspec#236]
Hello there,

I would like to generate one `it` for each file in a directory. My best try was like this:
```haskell
spec :: Spec
spec = do
  describe "gc" $ do
    fileNames <- getDirectoryContents "test/fixtures/input"
    let properFileNames = filter (`notElem` [".", ".."]) fileNames
    forM_ properFileNames $ \file -> do   
      it "test" $ do
        input <- readFile $ "test/fixtures/input/" ++ file
        output <- readFile $ "test/fixtures/output/" ++ file ++ ".out"
        ((parseAndCompile input) ++ "\n") `shouldBe` output
```

But it don't match the types correctly:

```haskell
    Couldn't match type `IO'
                  with `hspec-core-2.1.5:Test.Hspec.Core.Spec.Monad.SpecM ()'
    Expected type: hspec-core-2.1.5:Test.Hspec.Core.Spec.Monad.SpecM
                     () [FilePath]
      Actual type: IO [FilePath]
    In the return type of a call of `getDirectoryContents'
    In a stmt of a 'do' block:
      fileNames <- getDirectoryContents "test/fixtures/input"
    In the second argument of `($)', namely
      `do { fileNames <- getDirectoryContents "test/fixtures/input";
            let properFileNames = filter (`notElem` ...) fileNames;
            forM_ properFileNames $ \ file -> do { ... } }'
```

Is there a way to generate many `it` dynamically?

Thanks!

**Comment by sol** [comment]
Yes, use

    fileNames <- runIO (getDirectoryContents "test/fixtures/input")

Your use case is the reason we added `runIO` in the first place.  Note that tour `runIO` action is alway executed when the test tree is constructed, even e.g. with `--dry-run`.  For that reason you should do as little in `runIO` actions as possible.

**Comment by sol** [comment]
We should have a section on this in the user manual. Patches would be more than welcome.

**Comment by fotanus** [comment]
Thanks! I'll send a PR for this documentation. 

However, I didn't got yet how exactly can I jump the "." and ".." directories? Note I'm not great at Haskell... yet!

This works but include "." and "..". 
```
spec :: Spec
spec = do
  describe "gc" $ do
    fileNames <- runIO (getDirectoryContents "test/fixtures/input")
    forM_ fileNames $ \file -> do  
      it ("test " ++ file) $ do
          input <- readFile $ "test/fixtures/input/" ++ file
          output <- readFile $ "test/fixtures/output/" ++ file ++ ".out"
          ((parseAndCompile input) ++ "\n") `shouldBe` output
```

I tried to remove them using "if", but then I need to return a `SpecM` on the else. I failed badly in finding a way to specify an "empty SpecM". Of course I'm ok with better solutions than an if!!

**Comment by sol** [comment]
Just use the `let` as with your original code?

**Comment by fotanus** [comment]
You are right, sorry. For some reason, the lack of listing on all tests confused me, and I thought only one was running.

Great, thanks! Doing the PR for the doc. Hopefully on the correct place :-)

**Comment by sol** [comment]
Fine to close?

**Comment by fotanus** [comment]
Yes!
