### ISSUE TITLE
Exceptions in `beforeAll` are counted as test case exceptions

### ISSUE THREAD

**Issue by nh2** [hspec/hspec#243]
When I use a `beforeAll` hook (e.g. to start a database server) and that fails with an exception, all tests that depend on it are run anyway and it gets reported as

```
Failures:

  1) My first tests: returns 200 OK
       uncaught exception: IOException of type UserError (user error (ERROR: Database didn't come up within 1.0 seconds))

... all the other failures ...
```

It would be helpful / nicer if when a `beforeAll` action fails, that gets accredited separately (similar to how it's done for `afterAll`) and that the tests that depend on it aren't run.

--

I believe the situation is like this currently because `beforeAll` is (roughly) simply a `memoize` of `before`.

**Comment by soenkehahn** [comment]
What do you think about #244 as a fix?

**Comment by nh2** [comment]
Looks sensible to me so far ("see previous failure" is already better).

**Comment by sol** [comment]
@soenkehahn thanks a lot!
