### ISSUE TITLE
Why was `configVerbose` removed?

### ISSUE THREAD

**Issue by jaseemabid** [hspec/hspec#245]
I have a test comparing 2 deeply nested objects. Now the test fails reporting that the objects are not same and I have no way to see how they are different. When the 2 arguments to `shouldBe` are actually different, how can I print them both so that you know why the test failed. 

What is the recommended approach?

**Comment by sol** [comment]
@jaseemabid sorry for the late reply.  `shouldBe` should include both objects, using their `Show` instance.  Please post some self-contained example, if you still have an issue.

Regarding `configVerbose`, "verbose" mode is the default now (AFAIK).

Closing for now.
