### ISSUE TITLE
Using with `stack test --trace` fails

### ISSUE THREAD

**Issue by Wizek** [hspec/hspec#256]
An example: https://gist.github.com/Wizek/c8e5e3ee473bd8e07e55

It seems the problem is that stack (or cabal?) puts spaces around the `+RTS` argument, which HSpec has a hard time ignoring.

Do you think this something to be fixed in HSpec or stack?

**Comment by sol** [comment]
Your `hspec` test suite is a normal Haskell executable that handles RTS flags the same way as other Haskell executables.  AFAICT, this is something that has to be fixed in `stack`.

**Comment by sol** [comment]
I can not reproduce this with `stack` version `1.2.0`. Maybe this has been fixed upstream?

I'm closing this, please open a issue for `stack` if this still fails for you.
