### ISSUE TITLE
How to print quickcheck testcases

### ISSUE THREAD

**Issue by ismail-s** [hspec/hspec#257]
I have been using hspec with quickcheck, and so far it has worked fine using quickcheck's `property` function. However, I tried using the `verbose` function to see the generated testcases, and nothing changed. What can I do to fix this problem?

Thanks in advance.

**Comment by camelpunch** [comment]
A rather onerous workaround is to extract the property you want to debug into its own, named function, and then `quickCheck` that function directly from the REPL.

**Comment by ismail-s** [comment]
@camelpunch You've made my day by responding to this issue, as I had a little chuckle to myself that it was almost a year for this response to come.

I haven't used Haskell for a while (unfortunately), but what you've said makes perfect sense, although it is basically sounds like hspec doesn't support using the `verbose` function.

This issue can be closed if you want, you have technically given a kind of workaround.

**Comment by camelpunch** [comment]
I'm not the maintainer! I'd love to see support for getting the QuickCheck output.

**Comment by SamDM** [comment]
I would like to add that collecting test cases also does not work, for example:

```
module IssueSpec where

import Test.Hspec
import Test.Hspec.QuickCheck (prop)
import Test.QuickCheck       (collect)

spec :: Spec
spec = describe "I am trying to get stats" $
  prop "collect fails" $
    \(x :: Int) -> collect x $ True
```

Running `stack test` only prints the following:

```
Issue
  I am trying to get stats
    collect fails
Finished in ...
```

**Comment by SamDM** [comment]
And the following seems to fail as well

```
  prop "cover fails" $
    \(x :: Int) -> cover (x == 0) 42 "This message stays hidden" $ True
```

As it only prints 
```
Issue
  I am trying to get stats
    collect fails
    cover fails FAILED [1]

Failures:

  test/IssueSpec.hs:12: 
  1) Issue, I am trying to get stats, cover fails
       Insufficient coverage

Randomized with seed ...

Finished in ...
```

**Comment by sol** [comment]
All of this works on `master` by now.  The reason why it's not release yet is that this introduced quite a number of breaking changes to the formatters API.  For this reason I take this as a chance to do a long overdue cleanup of the formatter API.  I love small incremental changes, but in the case of public APIs I prefer to keep things as stable as possible and have big breaking changes on the rare occasion when it's real needed instead of small breaking changes more frequently.

So this won't be released yet, please use the Git version if you want to get all the QuickCheck output.

**Comment by SamDM** [comment]
Thanks! Great to hear that this already fixed.

**Comment by sol** [comment]
Released to Hackage as `2.5.0`.

**Comment by sol** [comment]
@begriffs as an update to your blog post https://begriffs.com/posts/2017-01-14-design-use-quickcheck.html.  As of version `2.5.0` Hspec will retain all QuickCheck output (including collect and classify results).

**Comment by begriffs** [comment]
Thanks for the heads-up. I'll make a set myself a reminder to update the article.

**Comment by begriffs** [comment]
Actually I've decided that this documentation is not something I want to work on for free. Trying to [change](https://begriffs.com/posts/2018-04-01-no-more-freebies.html) how I spend my time regarding volunteer vs paid work.

**Comment by frerich** [comment]
Yay, this is great timing. I was just looking for a way to make hspec print the output of my QuickCheck tests. 👍
