### ISSUE TITLE
hspec-discover: Make sure that `cabal haddock` does not fail

### ISSUE THREAD

**Issue by sol** [hspec/hspec#258]

**Comment by sol** [comment]
Done in ec3c87295e74f2a60ad581c00b1390079f57c3c2 and released to Hackage as 2.2.3.

@peti With this `doHaddock = False` should no longer be necessary for `hspec-discover`.

**Comment by peti** [comment]
I changed the build instructions for `hydra.cryp.to`. It's not going to be possible to detect possible breakage in `hspec-discover-example` and `hspec-discover-integration-test`, unfortunately, because these builds are currently broken for other reasons: http://hydra.cryp.to/eval/749517.

**Comment by sol** [comment]
@peti This looks critical.  With this, would `hspec-discover` work at all under Nix?

Is the error due to `hspec-discover` (the executable) now depending on `hspec-discover` (the library)?  Is the library build as a shared object, but it can not be found at runtime?

**Comment by sol** [comment]
@peti If that is the case and if that causes lots of friction for nix, I would change this back so that the executable does not depend on the library anymore.

**Comment by sol** [comment]
@peti Is it possible to prevent `hspec-2.2.3` going into nixpkgs until we have resolved this?

**Comment by peti** [comment]
> Is it possible to prevent hspec-2.2.3 going into nixpkgs until we have resolved this?

Nixpkgs is pretty much equivalent to Stackage these days. Our default
Haskell package set corresponds to Stackage Nightly, and then there are
some 90+ additional package sets for every LTS release. This means that
hspec-2.2.3 will not be used for anything until it shows up in the
Nightly snapshot.

Furthermore, we can manually override Nixpkgs to use 2.2.2, for the time
being. I'd love to avoid doing that if we can, but it's possible.

**Comment by peti** [comment]
About the error: I'm not sure what is causing it. The `hspec-discover` executable has a full RPATH hard-coded into it that allows it to find its shared library; I'm pretty sure that executable works.  Why the test suite fails anyway? I have no idea. Note that it happens only with GHC 7.8.x, though; the 7.10.3 build succeeds okay.
