### ISSUE TITLE
indentation for multiline representations of (failing) examples

### ISSUE THREAD

**Issue by lspitzner** [hspec/hspec#263]
e.g. if i have

```
foo `shouldBe` bar
```

where `foo`'s show instance gives a multiline result, the failure message is something like

```
  17) description blah, blub
       expected: first line of foo
       second line of foo
       ...
```

so there is _some_ indentation (to the level of "expected"), but i would prefer if the lines of foo were a proper block.

**Comment by sol** [comment]
Until recently, implementing this in `hspec` would have been hard, as the failure message was constructed by `HUnit` and `hspec` had no easy way to tell what the actual and expected value is.
But with a recent change to `HUnit` we have access to that information. So it should be fairly easy to implement this.

**Comment by moll** [comment]
Hi! At what point does the indenting kick in? I've got a simple `a shouldBe b` example going on with both containing newlines, yet newlines in the "expected"/"but got" output get encoded as `\n`. Thanks!

**Comment by sol** [comment]
@moll Thanks for taking the time to comment on this issue.  Can you please open a new issue:

 * gives a minimal example that reproduces the issue
 * describe the actual behavior of `hspec`
 * tell me what behavior you would want instead
