### ISSUE TITLE
Descend into lowercase dirs in hspec-discover

### ISSUE THREAD

**Issue by mitchellwrosen** [hspec/hspec#265]
Sometimes I like to organize my tests like:

``` haskell
test/
  Spec.hs
  type1/
    ... some Specs ...
  type2/
    ... someSpecs ...
```

but `hspec-discover` won't consider any spec that is inside a lowercase directory name.

Could it be changed so that `Test.Hspec.Discover.Run.findSpecs "test/Spec.hs"` on

```
test/
  Spec.hs
  inner/
    SomeSpec.hs
```

returns

``` haskell
[Spec {specFile = "test/inner/SomeSpec.hs", specModule = "Some"}]
```

rather than

``` haskell
[]
```

?

**Comment by mitchellwrosen** [comment]
Any thoughts on this @sol?

**Comment by sol** [comment]
My first thought: What you could already do without any changes to hspec is to put a Spec.hs into every sub dir and have multiple test-suite sections in your cabal file.

Not exactly what you are asking for though.

**Comment by sol** [comment]
@mitchellwrosen Does my suggestion (multiple test suites) work for you?  If yes, I would close this as `wontfix`.

**Comment by mitchellwrosen** [comment]
Yeah, you can close
