### ISSUE TITLE
preserving HSPEC_FAILURES

### ISSUE THREAD

**Issue by mwotton** [hspec/hspec#266]
I have the use case that I like to leave a window open with ghcid running hspec tests. This works great, except that when I edit a dependency, ghcid gets confused, and I need to kill it, run stack build, and restart it. Unfortunately, this means I drop the value of HSPEC_FAILURES - I tried getting it back from /proc/$PID/environ, but it appears to be a copy taken at startup, and doesn't reflect new settings.

an example of what i'm doing:

```


GHCID=""

function runghcid {
    echo "ghcid running" >> log
    ghcid --command='stack exec ghci --test -- -isrc -itest test/Spec.hs'  --test ':main --rerun --color' &
    GHCID=$!
}

function finish {
    kill $GHCID
}

stack build mycoolproject
runghcid
stack build --dry-run --file-watch mycoolproject 2>&1 | sed -u 's/ExitSuccess/\x0/g' | while read -d $'\0' x; do
    echo "$x" | grep -q "missing dependencies"
    if [ $? -eq 0 ]; then
        echo "killing ghcid & reinstalling stuff" >> log
        echo "GHCID: $GHCID"
        echo $GHCID >> log
#        cat /proc/$GHCID/environ >> log
        cat /proc/$GHCID/cmdline >> log
        echo kill $GHCID >> log
        kill  $GHCID
        wait $GHCID
        stack build mycoolproject
        runghcid
        echo "new ghcid is $GHCID" >> log
    else
        echo "no missing deps, continue to run" >> log
    fi
done

trap finish EXIT
```

Any thoughts? I can obviously hack something up in a fork that makes hspec dump its failures to a file somewhere then parse them, but it'd be preferable to have a blessed way. (Though, looking at it, perhaps i can do it in the ghcid command ...)

**Comment by mwotton** [comment]
ended up writing https://github.com/mwotton/hspec-stack-rerun - perhaps it's useful enough to be a part of hspec proper?

**Comment by sol** [comment]
Hi Mark, have you looked into sensei? 

How does your solution compare to it? Do you use ghci under the hood?

**Comment by mwotton** [comment]
No, I haven't. I don't use ghci - it's just a hack to save the
HSPEC_FAILURES environment variable to a file, and reload it from the same
file on the next run.

**Comment by sol** [comment]
For reference: https://github.com/commercialhaskell/stack/issues/1928#issuecomment-253179711

**Comment by sol** [comment]
Now that we have support for config files (https://github.com/hspec/hspec/commit/3f77d4962cfb9dfb9ec6ff9043b089d360a2bd7b), I think it's sensible to add a command-line option that dumps the failure report to a file.
