### ISSUE TITLE
Advice on comparing Double

### ISSUE THREAD

**Issue by erikd** [hspec/hspec#267]
I need to compare two values of type Double, and something like
```
     a `shouldBe` b
```
is not giving me the result I'd like and
```
abs (a - b) < 1e30 `shouldBe` True
```
is suboptimal.

I also tried to write my own `shouldBeClose`:
```
shouldBeClose :: Double -> Double -> Expectation
actual `shouldBeClose` expected =
  unless (abs (actual - expected) < 1e-30) .
    expectationFailure $ "expected: " ++ show expected ++ "\n but got: " ++ show actual
```
but that only hangs and I'm not sure why.

Clues?

**Comment by erikd** [comment]
The hang is due to my code and nothing to do with Hspec.

**Comment by soenkehahn** [comment]
If it's ok that your epsilon (`1e-30`) is always the same I would go with something like `shouldBeClose`.

(If you care about source location reporting for failing tests you have to tinker around with `ghc`s support for stacks and that's still somewhat in flux over `ghc` versions. Do you care about that?)

**Comment by erikd** [comment]
Location reporting is kind useful. I'd also be very interesting in seeing ifthere might be a way to specify a different epsilon for different tests.

**Comment by erikd** [comment]
https://github.com/hspec/hspec-expectations/pull/23
