### ISSUE TITLE
Send an exception to terminating threads

### ISSUE THREAD

**Issue by cocreature** [hspec/hspec#269]
If you use `bracket` in one of your tests (`around` doesn’t make sense if you want it to be part of your test) you would expect that your cleanup action is always run, especially in the (at least for me common case) of issuing a user interrupt. However because `hspec` runs the tests in separate threads they are just killed and you end up leaking resources.

A simple solution would be to use `withAsync` instead of `forkIO` in `runParallel`. 

I’d be happy to provide a PR for that if you agree with these semantics.

**Comment by cocreature** [comment]
It looks like this is not actually the problem in my case since I’m running in sequential mode.

I’ll leave this issue open nevertheless since this is still what I would consider a bug in parallel mode.

**Comment by sol** [comment]
I believe this is fixed by ce5dce4289394a3b33922d695acc45ce60ea66ea.

Closing.
