### ISSUE TITLE
Mayfail tests

### ISSUE THREAD

**Issue by NorfairKing** [hspec/hspec#271]
It would be nice to be able to mark a subtree as 'allowed to fail but still run them to see what the result is'. Is it possible to implement such a feature?

For example:
```
mayFail :: Expectation -> Expectation
```

**Comment by sol** [comment]
Sorry for the late reply. I believe the closest you can currently get is:

```haskell
mayFail :: Expectation -> Expectation
mayFail expectation = do
  r <- try expectation
  case r of
    Right () -> return ()
    Left (HUnitFailure _ reason) -> pendingWith ("\n" ++ formatFailureReason reason)
```

@NorfairKing is this suitable for you?  Other approaches (keeping it red but passing, source locations, ...) will probably require changes to `hspec`.

**Comment by NorfairKing** [comment]
@sol This looks great!
In hindsight, I should have been able to figure that out for myself.
Thank you very much for your help!
