### ISSUE TITLE
Fix travis CI

### ISSUE THREAD

**Issue by soenkehahn** [hspec/hspec#274]
Currently builds fail on `master` for `ghc-7.0.1` and `ghc-7.2.1`.

The first failure seems to be caused by `bytestring` just not building on `7.0.1` anymore. (See also https://github.com/lpsmith/bytestring-builder/issues/9)

Haven't looked into the second failure.

Should we remove these compilers from CI? Since there's both `7.0.4` and `7.2.2`?

**Comment by sol** [comment]
Yes, sounds good.

**Comment by sol** [comment]
Done.
