### ISSUE TITLE
Test runner fails to restore background and foreground colors on Windows 10

### ISSUE THREAD

**Issue by hanst99** [hspec/hspec#275]
On Windows 10, using powershell, hspec sets the background color to black and foreground color to white after running tests.

I'm not sure where exactly in the source the setting of colors happen, but there might be something wrong there.

For now I'm using this script to work around this:

```powershell
$console = (get-host).UI.RawUI
$prev_bg = $console.BackgroundColor
$prev_fg = $console.ForegroundColor
stack test
$console.BackgroundColor = $prev_bg
$console.ForegroundColor = $prev_fg
```
but it might still be worth investigating what's happening here, even if it's just a minor nuisance.

**Comment by sol** [comment]
This might be an issue with the ansi-terminal passage (or the way we use it). Help on this would be much appreciated!

**Comment by sol** [comment]
@hanst99 I would love to get that fixed. Any chance you can help with that?

The first thing to figure out is whether the issue occurs on Windows with a minimalistic program that uses `ansi-terminal`.

**Comment by sol** [comment]
I opened an upstream issue: https://github.com/feuerbach/ansi-terminal/issues/19
