### ISSUE TITLE
Recommened way to Loop with Spec

### ISSUE THREAD

**Issue by EarthCitizen** [hspec/hspec#277]
I have a series of specific values that I want do not want to randomly generate with QuickCheck. I also do not want to write out a bunch of permutations of the test data. I would like to do something like:

`it "for type of x" $ forEach [1..20] $ \x -> x `shouldBe` x`

Similar to how QuickCheck hooks in, but rather being able to specify the values. Is this possible? If not, how can I loop inside the spec? Or maybe I can implement my own forEach? How would I implement that?

Thanks

**Comment by sol** [comment]
You can use forM_

**Comment by EarthCitizen** [comment]
Like `it "for type of x" $ forM_ [1..20] $ \x -> xshouldBex`?
