### ISSUE TITLE
Require upcoming HUnit 1.4.0.0

### ISSUE THREAD

**Issue by sol** [hspec/hspec#279]
@snoyberg previously you requested to support older versions of `HUnit`, due to Haskell platform. Is this still a concern?

**Comment by snoyberg** [comment]
I'd still recommend keeping some support for older versions, but it's not nearly as important now. LTS Haskell releases will simply not take in a new hspec version that requires too new an HUnit version. I don't think too many people are using the HP Full installer anymore (or if they _are_ using it, they're running into enough pain that they're switching to something else soon after).

**Comment by sol** [comment]
I went through the pain, to make it work with older versions.
