### ISSUE TITLE
Use `displayException` rather than show in `formatException`

### ISSUE THREAD

**Issue by mitchellwrosen** [hspec/hspec#289]
What do you think about using `displayException` rather than `show` when formatting exceptions?

**Comment by sol** [comment]
What is your rational for this?

**Comment by mitchellwrosen** [comment]
Just that (I think) displayException was added for displaying to humans, so it's supposed to be nicer to read

**Comment by sol** [comment]
In the context of an unexpected exception from a test case, what are you interested in? 

1. A human friendly error message

2. All the available information (type, constructor name, ...) so that you can use that information to debug the issue

**Comment by mitchellwrosen** [comment]
Ah, that's true. Ok, closing

**Comment by sol** [comment]
@pbrisbin new issue please, so that it's more visible. I'll reply as soon as I have some spare cycles for it.
