### ISSUE TITLE
rerun behaviour

### ISSUE THREAD

**Issue by mwotton** [hspec/hspec#291]
Usually when I use --rerun, the actual behaviour I want is to run the failing tests until they all pass, then run the whole test suite to ensure I didn't break anything else. It's easy enough to script, but perhaps this could be a different rerun mode? It can be quite misleading when it looks like your tests pass, but you've silently broken something that ran correctly last time you did a full test run.

**Comment by sol** [comment]
You might want to give `sensei` a try, it does exactly that.

**Comment by mwotton** [comment]
fair enough.

**Comment by sol** [comment]
Hey @mwotton, I just came back to this issue to reopen it (more on that later), and it's only now that I see your full response. The e-mail I got before only contained a stripped-down version.

Things may not be as smooth as they could be, but I think it should be possible to get it working for your project. Did you try something like:

```
$ stack exec sensei test/Spec.hs
```

You may want to create a `.ghci` file, e.g.:
```
$ cat .ghci
:set -isrc -itest
```

Where exactly did you hit the wall?

**Comment by sol** [comment]
Now back to why I reopened this issue: After thinking about this, I'm tempted to change `--rerun` to rerun everything on success. That would not only solve your use case, but also simplify `sensei` a lot.

Do you think this is a suitable default for `--rerun`, or should we hide it behind an other flag?

**Comment by sol** [comment]
@mwotton I implemented this. Feedback is welcome.

**Comment by mwotton** [comment]
apologies for delay, i've been travelling - looks good, thank you very much!
