### ISSUE TITLE
Base Assertions off MonadThrow from exceptions vs HUnit's IO Assertions

### ISSUE THREAD

**Issue by jfischoff** [hspec/hspec#292]
Currently testing in monads that are not IO is annoying. This could be drastically improved by using assertions that based off of MonadThrow vs IO. 

So `shouldBe` would have the signature like 

```haskell
shouldBe :: (Eq a, Show a, MonadThrow m) => a -> a -> m ()
```

It would still throw the same exceptions as the HUnit version it would just use `throwM` vs `throw` or `throwIO`

The goal would to rewrite all the assertions using MonadThrow.

**Comment by sol** [comment]
@jfischoff I am not sure if I exactly understand what that implies.

I think it's possible to generalize `shouldBe` over `MonadThrow`. Still,  at some point (e.g. when we run the tests) we have to instantiate `m` with some concrete type, right? What type would that be, or how would that type be determined?

Specifically I'm puzzled about the following:

1. Do you only want changes to `hspec-expectations`, or also `hspec` itself?
1. In case you want changes to `hspec`, what exact changes would that be?

**Comment by sol** [comment]
By the way, do you have a concrete example for your use case?

**Comment by jfischoff** [comment]
The change only needs to be in hspec-expectations. I am going to close this issue because I didn't understand the project layout. 

I have made the changes myself and it can be offered as a separate packge. I think it should be the default, but I think having it as a separate package to start with also makes sense. I will release it and we can go from there.

**Comment by sol** [comment]
@jfischoff separate package sounds good.

As for making it the default, I think that would hurt type inference for simple tests. E.g. this code
```haskell
spec :: Spec
spec = do
  it "some example" $ do
    "foo" `shouldBe` "bar"
```
would now require a type annotation:
```haskell
spec :: Spec
spec = do
  it "some example" $ do
    "foo" `shouldBe` "bar" :: IO ()
```

We also have [hspec-expectations-lifted](https://github.com/hspec/hspec-expectations-lifted). And providing something similar for `MonadThrow` sounds like a good thing.

What is currently a little bit cumbersome, is using an alternative implementation of `hspec-expectations`. `Test.Hspec` re-exports `shouldBe`, which requires hiding, e.g.:
```haskell
import Test.Hspec hiding (shouldBe)
import Test.Hspec.Expectations.Lifted
```
My hope is, that this can be addressed medium-term by refactoring `hspec`'s module structure.

Ideally, we would want to parametrize `hspec` over an implementation of `hspec-expectations` a la [backpack](http://plv.mpi-sws.org/backpack/). But I don't know if anything is moving forward on that front.
