### ISSUE TITLE
Test count output bleeds through to hspec output

### ISSUE THREAD

**Issue by erikd** [hspec/hspec#301]
For one of my hspec test suites I've set `configQuickCheckMaxSuccess = Just 100000`. When the tests are run it now prints `xxxxx/100000` for each test, but if the description for the `prop` test is too short, part of the count gets left behind when the test is completed so I get for example:

```
  complement
  negate0000
  signum0000
  logical and/or/xor
```
where the `0000` after "negate" and "signum" is the last four digits of `100000`.

**Comment by sol** [comment]
@erikd I guess we need to pad with spaces if the description is shorter than the QC count output.  Patches welcome!

**Comment by erikd** [comment]
I've got  a trivial test program that displays the problem:
```
{-# LANGUAGE ScopedTypeVariables #-}
import Control.Monad

import Test.Hspec
import Test.Hspec.QuickCheck
import Test.Hspec.Runner

import System.Exit


main :: IO ()
main = do
  summary <- hspecWithResult config testAll
  when (summaryFailures summary == 0)
    exitSuccess
  exitFailure
  where
    config = defaultConfig { configQuickCheckMaxSuccess = Just 100000 }

testAll :: Spec
testAll =
  prop "short" $ \ (a, b :: Int) ->
    (a + b) `shouldBe` (b + a)
```
but can't figure out where the property description is being printed. Clues?

**Comment by erikd** [comment]
Never mind. The use of git submodules made this a little difficult to figure out but I have a fix now.

**Comment by erikd** [comment]
I've just spent another hour on this problem. I've now come up with two solutions that fix the actual problem I see when running tests, but fail in the test suite.
