### ISSUE TITLE
index pages broken (no links) on hackage and stackage 

### ISSUE THREAD

**Issue by jwaldmann** [hspec/hspec#308]
identifiers are listed with name and module name, but none of these have hyperlinks:

* https://hackage.haskell.org/package/hspec-2.4.1/docs/doc-index-S.html
* https://www.stackage.org/haddock/lts-8.2/hspec-2.4.1/doc-index-S.html

When I do `stack haddock hspec` locally, the same thing happens, but the thing I was looking for (`shouldBe`) does appear in the index of `hspec-expectations`. I guess that's a haddock quirk, but it sure is inconvenient: from looking at the page on hackage, there is no way to find the module that has the actual documentation? But then, https://www.stackage.org/lts-8.2/hoogle?q=shouldBe looks reasonable.

**Comment by sol** [comment]
This looks like a Haddock bug.

If you agree, please report it there and close this issue.

**Comment by jwaldmann** [comment]
Ah, I guess it's https://github.com/haskell/haddock/issues/563

**Comment by sol** [comment]
I don't think this ticket is related.  This one is about re-exported modules.
