### ISSUE TITLE
sequential execution of a subset of tests (inside parallel)?

### ISSUE THREAD

**Issue by jwaldmann** [hspec/hspec#311]
I have a ton of tests (in a tree), and I would love to put `parallel` at the top, but some subtree uses a library that's not thread-safe, so their tests have to be run sequentially. Is there an `unparallel` operator that I can  apply to this subtree ... ? Sure I can pull out this subtree manually and run it separately, but that's clumsy.

**Comment by sol** [comment]
I think it makes sense to add this.  How about we call it `sequential`?
