### ISSUE TITLE
how to show diff output

### ISSUE THREAD

**Issue by abnud1** [hspec/hspec#314]
I'm currently using hspec in a compiler project with hspec-megaparsec.  

In my project I define `SymbolTable` to be some kind of a `HashTable` from unordered-containers package, many times I need to test that correct symbols are added to the table.  

When the tests fail because the table is big I have to decipher the output, I didn't find out how to show diff output in hspec.  

It would be good to show only the diff without `expected` and `got` because the table's size could distract me from the diff output, I'm ok with `expected` and `got` for the parsing result.  

How to do this in hspec ? I found that `--diff` option is turned on by default but I see no diffs !!, also this library didn't work : https://hackage.haskell.org/package/hspec-expectations-pretty-diff

**Comment by sol** [comment]
What version of `hspec` are you using?  Do diffs work for a simple example, e.g.

```haskell
spec :: Spec
spec = do
  it "foo" $ do
    [2..4] `shouldBe` [1..3]
```

**Comment by sol** [comment]
> This is what you should see:

![hspec](https://cloud.githubusercontent.com/assets/461132/25796267/707d7984-340b-11e7-830b-10dd4bcdab1d.png)

**Comment by abnud1** [comment]
I'm using version 2.4.3, yes your simple example works, for the real thing the output of the failed test is all red both expected and got

**Comment by sol** [comment]
This is an issue with `hspec-megaparsec`.  Please report it there.
