### ISSUE TITLE
Require QuickCheck >= 2.10?

### ISSUE THREAD

**Issue by sol** [hspec/hspec#321]
`hspec-2.5.0` will support `--diff` and source locations for failing QickCheck properties.  Doing so requires the latest version of QuickCheck (>= `2.10`).

Specifically, we need https://github.com/nick8325/quickcheck/commit/ff9b574ea91d6f121de0dd11c7edf5b9c89fe0e3.  Supporting older versions of QuickCheck, while possible, degrades the user experience for that users significantly + it's quite some extra version.  For that reason I'm considering to require `QuickCheck >= 2.10`.

**Comment by sol** [comment]
@snoyberg In the past you were asking me to support older versions of QuickCheck / HUnit.  How much of a concern is this still to you?

**Comment by snoyberg** [comment]
It's definitely preferable, especially with a library like QuickCheck where people seem to be very slow to upgrade. If some packages start supporting _only_ the newer one, we get into a situation where we either have to hold back those packages, or drop other packages. That said, when we get aggressive about pruning post-LTS-9 release, we'll likely add a bunch of packages to skipped-tests.

In other words: I'd prefer it, but your call.

**Comment by phadej** [comment]
FWIW, stackage nightly had `QuickCheck-2.10` for some time already.
