### ISSUE TITLE
Golden tests

### ISSUE THREAD

**Issue by phadej** [hspec/hspec#328]
Does hspec architecture supports adding new type of tests, or should they be added to the core?

I'd like to have so called golden tests in `hspec` too (they are in `tasty`: http://hackage.haskell.org/package/tasty-golden). Motivated by https://github.com/haskell/haddock/pull/668

**Comment by sol** [comment]
@phadej Yes, it's possible to extend `hspec` by adding new instances for the `Example` type class.  What currently is not possible, is adding new command-line options.  So if you need new command-line options, we would need to hard-code them in `hspec-core`.

**Comment by CristhianMotoche** [comment]
Hi @sol. I'd like to know you have been working on this. In case you don't, I'd love to start working on it.

**Comment by sol** [comment]
@CristhianMotoche hey, I haven't worked on this. But I've been looking into allowing to add custom command line options. Not released yet, but this might come in handy for this feature.

You could get started by hard coding any options  for now and we then change that once I finished up my code.

**Comment by CristhianMotoche** [comment]
Great! Thanks for letting me know that @sol

**Comment by CristhianMotoche** [comment]
Hi @sol . I'm sorry for taking a little while in respond. I've been thinking in the interface that we want to export to users. I came up with the following idea:

```haskell
data Golden str = 
  Golden {
    output :: str -- ^ Lazy bytestring output
    write :: FilePath -> str -> IO (), -- ^ How to write into the golden file the file
    read :: FilePath -> IO str
  }

hGolden :: GoldenTest -- ^ Parameters for the Golden Test
               -> GoldenResult -- ^ Possible result of the test execution

data GoldenResult =
   
```

**Comment by CristhianMotoche** [comment]
Hi @sol . I'm sorry for taking a little while in respond. I've been thinking in the interface that we want to export to users. I came up with the following idea:

```haskell
data Golden str = 
  Golden {
    output :: str -- ^ Lazy bytestring output
    write :: FilePath -> str -> IO (), -- ^ How to write into the golden file the file
    read :: FilePath -> IO str, -- ^ How to read the file,
    name :: String, -- ^ Test name (make sure it's unique otherwise it could be override)
    directory :: FilePath -- ^ Directory where you write your tests
  }

instance Example Golden where
 type Arg Golden = ()
 evaluateExample e = evaluateExample (\() -> e)

instance Example (arg -> Golden) where
 type Arg (arg -> Golden) = arg
 evaluateExample golden params action progressCallback =
   fromGoldenResult <$> runGolden golden

defaultGolden :: String -> String -> Golden
defaultGolden name_ output_ =
  Golden {
    output = output_,
    name = name_,
    write = writeFile,
    read = readFile,
    directory = "hspec/.golden/"
  }

runGolden :: Golden -> IO GoldenResult
runGolden = ... -- ^ Here is the "fun" part

fromGoldenResult :: GoldenResult -> Hspec.Result
fromGoldenResult = ... -- ^ Some pattern matching

data GoldenResult =
   MissmatchOutput
   | SameOutput
   | FirstExecution
```

Usage example:

```haskell
describe "myFunc" $
  it "generates the right output" $
     let output = show $ myFunc params
       in hGolden (defaultGolden "myFunc" output)
```

`runGolden` will take the golden `name` and create a subdirectory under `directory` (e.g. `hspec/golden/myFunc/`).

If the test is executed for the first time it will pass creating a single file called `golden` inside that directory:

```
hspec/golden/myFunc/
		|_ golden
```

After that, there are a couple of things that can happen:

1) If `myFunc` changes and the test is executed a second time it will generate a different output, the test will fail writing the actual output to a file called `actual`

```
hspec/golden/myFunc/
		|_ golden
		|_ actual
```

The user will have to update `golden` with `actual` if the actual output is one that the user expects: `mv hspec/golden/myFunc/{actual,golden}`. I suppose we want to automate this by adding a flag to the CLI.

2) If `myFunc` doesn't change and the test is executed a second time the test will succeed without writing any output.

```
hspec/golden/myFunc/
		|_ golden -- ^ Stays the same
```

Please, let me know your thoughts.

**Comment by sol** [comment]
[`hspec-golden`](https://hackage.haskell.org/package/hspec-golden) has been on Hackage for some time now. I haven’t had a chance to try it myself yet, but I am looking forward to.

I’m going to close this issue.

@CristhianMotoche If there are things that we can do in Hspec that benefit `hspec-golden` then please don’t be shy to open a new issue here.
