### ISSUE TITLE
Allow use of --match and --skip from .hspec files

### ISSUE THREAD

**Issue by RobMurray98** [hspec/hspec#335]
Currently the only way to tell `stack test` which tests to skip or match is through the command line explicitly. I would like to see support of ability to do this through .hspec files.

**Comment by sol** [comment]
The reason `--match` and `--skip` don't work from `.hspec` is that `.hspec` only supports options that you reasonably want to use for all of your projects.

@RobMurray98 What is your current workflow and how do you intent to use this feature? Have you looked into `--rerun` and `--failure-report` (both of which can be specified in `.hspec`)?

**Comment by sol** [comment]
Or take a look at `hspec/sensei`.

**Comment by RobMurray98** [comment]
@sol I have one test that goes through all possible inputs and takes an hour or so, which obviously you don't want to run normally. `hspec/sensei` would definitely work for what I want by just putting the expensive test in a different testing file, so that's great. Can I ask what the reasoning behind not allowing `--match` and `--skip` in the project's directory level `.hspec` file is? It obviously makes sense that the home directory `.hspec` file doesn't allow it. Maybe the ability to specify the location of the specification file you want to use, as in `hspec/sensei`, could be added to `hspec/hspec` in some way?

**Comment by sol** [comment]
Hey, sorry for the late reply!

> Can I ask what the reasoning behind not allowing --match and --skip in the project's directory level .hspec file is? It obviously makes sense that the home directory .hspec file doesn't allow it. 

I'm not too eager to add even more corner cases.  I guess I can be convinced to allow `--match` and `--skip` in `.hspec`, but it would be for both the global and the per project one.

My main concern is that at some point somebody will open an issue saying "some of my specs are never executed" and I'll have to guide them through "please check your environment variables", "please check `.hspec`", "please check ~/.hspec`...

But my overzealously trying to protect users from them self.  So again, I guess I can be convinced to lift the current restriction.

> Maybe the ability to specify the location of the specification file you want to use, as in hspec/sensei, could be added to hspec/hspec in some way?

Not sure if I understand what you mean, but `sensei` allows you to specify the spec file on the command line.

**Comment by manpacket** [comment]
Wanted to use --skip in .hspec file for a similar reason, instead got " hspec: unrecognized option `--skip' in config file" - took a while to figure out that it's an intentional design decision. Try printing warnings about tests disabled/enabled through config files/env variables?

**Comment by sol** [comment]
An other complication with this is that `--match` and `--skip` accept free-form arguments that may e.g. contain whitespace. This will require some sort of quoting.  On the command-line the shell takes care of quoting.

For config files and environment variables we would need to implement quoting ourself, which poses the question what exact quoting rules we would want to use.

**Comment by sol** [comment]
Because of the whitespace/quoting issues, I'm not eager to add support for `--skip`/`--match` to `.hspec` and `HSPEC_OPTIONS`.

However, starting with `hspec-2.8.4` you can now set options by setting separate environment variables.  So e.g. setting `HSPEC_MATCH=...` works now.

@RobMurray98 I hope this addresses you use case.
