### ISSUE TITLE
Missing Semigroup instance on GHC HEAD

### ISSUE THREAD

**Issue by harpocrates** [hspec/hspec#336]
As part of the semigroup-monoid proposal, `Semigroup` becomes a superclass of `Monoid`. This is due to happen in 8.4.

It looks like `hspec` still has a `Monoid` instance [here](https://github.com/hspec/hspec/blob/51b7933cf92934f292900a2a6c03cf8c9627d765/hspec-core/src/Test/Hspec/Core/Runner.hs#L239) without a `Semigroup` instance, so `hspec` doesn't compile on GHC HEAD.

**Comment by sol** [comment]
Hi @harpocrates , thank you for taking the time to open this issue.  A PR would be very much welcome.  I can push a minor release to Hackage once this is fixed.

**Comment by DanBurton** [comment]
Bumped into this trying to build with the ghc alpha.

```
    [22 of 22] Compiling Test.Hspec.Core.Runner ( src/Test/Hspec/Core/Runner.hs, .stack-work/dist/x86_64-osx/Cabal-2.1.0.0/build/Test/Hspec/Core/Runner.o )

    /private/var/folders/bz/c3q0fbt94dbgx69km1r5rbxw0000gn/T/stack7703/hspec-core-2.4.4/src/Test/Hspec/Core/Runner.hs:229:10: error:
        • No instance for (Semigroup Summary)
            arising from the superclasses of an instance declaration
        • In the instance declaration for ‘Monoid Summary’
        |
    229 | instance Monoid Summary where
        |          ^^^^^^^^^^^^^^
```

I'll try and whip up a quick little PR.

**Comment by DanBurton** [comment]
I've opened #342 which addresses this.
