### ISSUE TITLE
Tests are run with masking state set to MaskedInterrutible

### ISSUE THREAD

**Issue by cocreature** [hspec/hspec#349]
The following test program demonstrates that `hspec` runs tests with the masking state set to `MaskedInterruptible` even when exceptions are unmasked before running the tests.

```
import Control.Exception
import Control.Monad.IO.Class
import Test.Hspec

main :: IO ()
main = do
  print =<< getMaskingState
  hspec $ do
    describe "foobar" $ do
      it "foobar" $ do
        print =<< getMaskingState
```

I am not sure if this is intentional or not but it is at least a bit unexpected so if it is intentional it would be nice to document this.

I tested this using `hspec-2.4.8`.

**Comment by sol** [comment]
Hey!  Thanks for reporting this!  This seems to be broken since version `2.4.0`.

**Comment by sol** [comment]
Part of the story is https://github.com/hspec/hspec/pull/270/commits/2765fe58473f87a4ec31cfc8fad8624049a15288

**Comment by sol** [comment]
@cocreature do you need a bugfix release for this?

**Comment by cocreature** [comment]
No, I don’t. Thanks a lot for the quick fix and I’m really sorry for having introduced this bug.

**Comment by sol** [comment]
> sorry for having introduced this bug

@cocreature the whole story is more nuanced.  Stating that you introduced the bug is factually wrong.
