### ISSUE TITLE
SpecM should be a Profunctor

### ISSUE THREAD

**Issue by koterpillar** [hspec/hspec#353]
As far as I understand it, the `SpecM a r` values are tests that take `a` as input and return `r`. This makes them lawful instances of [`Profunctor`](https://www.stackage.org/haddock/lts-11.11/profunctors-5.2.2/Data-Profunctor.html).

A use case I have for that is running a test that requires input with a single `before` but different actual arguments:

```haskell
-- | Perform some common checks on a list
listChecks = do
  it "is non empty" $ \lst -> not (null lst)
  it "is not too long" $ \lst -> length lst < 10

-- | Something to verify the results of
expensiveComputation :: ([a], [b])

-- | All the tests
spec = do
  beforeAll expensiveComputation $
    context "first list" $ lmap fst listChecks
    context "second list" $ lmap snd listChecks
```

**Comment by sol** [comment]
@koterpillar thanks you for taking the time to open this issue and the corresponding PR, and sorry for the late reply.

As I understand it, this adds the following list of new dependencies:

```
base-orphans
bifunctors
cabal-doctest
comonad
contravariant
distributive
profunctors
semigroups
StateVar
tagged
th-abstraction
```

`hspec` has a small dependency footprint, this is a major design goal + I want to keep it that way. For this reason this is a `wontfix`.

I am open to consider adding the functionality as a normal function though.  PRs welcome.

**Comment by sol** [comment]
I think this is a generalization of #242.

**Comment by sol** [comment]
`lmap` can be implemented as

```haskell
lmap :: (b -> a) -> SpecWith a -> SpecWith b
lmap f = aroundWith (. f)
```

**Comment by sol** [comment]
We could add this as a primitive, e.g.

```haskell
mapSubject :: (b -> a) -> SpecWith a -> SpecWith b
mapSubject f = aroundWith (. f)
```

**Comment by sol** [comment]
`contramapSpec` would be an other option, but I'm not sure if that is more clear or confusing.
