### ISSUE TITLE
Symlinked LICENSE caused build FAIL in nix

### ISSUE THREAD

**Issue by Rizary** [hspec/hspec#357]
This issue is based on my explanation here:

https://github.com/NixOS/nixpkgs/issues/42550

I'm using master branch, maybe this is not hspec issue but should there be a consideration to remove symlinked LICENSE, it will make it easier than to fix nix behavior.

**Comment by sol** [comment]
I removed the symlinks.

**Comment by Rizary** [comment]
@sol thanks!!
