### ISSUE TITLE
The config has no option to set the maximum shrinks for quickcheck

### ISSUE THREAD

**Issue by NorfairKing** [hspec/hspec#380]
The config has no option to set the maximum shrinks for quickspec.
The default is `maxBound :: Int`, so I'd like to be able to configure it.

**Comment by sol** [comment]
@NorfairKing as a quick workaround you can modify `maxShrinks` manually.  Take a look at https://hackage.haskell.org/package/hspec-core-2.5.7/docs/src/Test.Hspec.Core.QuickCheck.html#modifyMaxSuccess for a rough idea how this could be achieved.

**Comment by NorfairKing** [comment]
Aha! `modifyArgs` seems to be new.
That's a good workaround!

**Comment by sol** [comment]
It's not exported, but you can copy and paste for now.

**Comment by sol** [comment]
https://github.com/hspec/hspec/pull/381 is easy.

We may still want to add a command-line option, but that would be for `2.6`.

**Comment by sol** [comment]
On Hackage as `2.5.8`.

**Comment by NorfairKing** [comment]
Wauw, thanks for the quick fix.

**Comment by NorfairKing** [comment]
Oh, this is done. Let me close the issue.
