### ISSUE TITLE
Human-readable output of unicode characters in expectation results

### ISSUE THREAD

**Issue by artempyanykh** [hspec/hspec#384]
When there are non-ascii chars in strings, the resulting output shows codes of those chars instead of their human-readable representation, e.g.

```
expected: "\1084\1072\1075\1072\1079\1080\1085"
  but got: "\1052\1072\1075\1072\1079\1080\1085"
```

In GHCi there is a way to specify a *different show function*, e.g. `:set -interactive-print Text.Show.Unicode.uprint`.

Is there a way to similarly alter Hspec's output function to properly handle unicode chars?

**Comment by sol** [comment]
Hey! Thanks for opening this issue!

Currently this is not supported and I'm not sure how deep we need to dig to add it.  I like the idea though and I'm happy to look into it eventually, but can't commit to a timeline.

As a workaround, you can use a `newtype` on your strings for now, that alter the show instance, e.g. (untested):

```
newtype UString = UString String

instance Show UString where
  show (UString s) = ushow s
```

**Comment by artempyanykh** [comment]
Hey @sol ! Got it, thank you! And thanks for the workaround, much better then decoding utf-8 codes 😃
