### ISSUE TITLE
Add flag to run tests in randomised order

### ISSUE THREAD

**Issue by bubba** [hspec/hspec#395]
It would be nice to be able to run the tests in a random order, to prevent accidental dependencies in the orders of the tests. 
Would this option be exposed through Hspec's config or Hspec-discover?

**Comment by sol** [comment]
I think a command-line option might be the way to go.  That way you can add it to either `.hspec` (project specific) or `~/.hspec` (user global) or on the command line (e.g. CI only).

**Comment by sol** [comment]
@bubba sorry for the late reply.  Definitely something we want to have!  Thanks for opening this issue.

**Comment by jhrcek** [comment]
I just found this issue by googling if hspec supports randomizing test order. 
Then I found https://hspec.github.io/options.html mentions `--randomize` options, so perhaps this issue should be closed since this feature already exists?

**Comment by bubba** [comment]
@jhrcek Christmas has come early. Thanks guys!
