### ISSUE TITLE
Docs are incomplete

### ISSUE THREAD

**Issue by BebeSparkelSparkel** [hspec/hspec#396]
I am looking through the index http://hackage.haskell.org/package/hspec-2.5.5/docs/doc-index-S.html and it seems like there are a lot of functions that are listed but are not included in the documentation.
Would it be possible to have those functions included int the hackage docs?

**Comment by sol** [comment]
@BebeSparkelSparkel Hey! What specifically are you looking for?  Some stuff is defined in other packages and re-exported, e.g. `shouldBe` in https://hackage.haskell.org/package/hspec-expectations-0.8.2/docs/Test-Hspec-Expectations.html.  Here the `hspec` docs only contain reference to that whole module like so https://hackage.haskell.org/package/hspec-2.6.0/docs/Test-Hspec.html#g:2.
