### ISSUE TITLE
bad QuickCheck dependency version for hspec-meta

### ISSUE THREAD

**Issue by kquick** [hspec/hspec#399]
The hspec-meta package specifies `QuickCheck >= 2.10`, but the change in https://github.com/hspec/hspec/commit/226510631f24b674827e99d17d10f9f92440c5a9 has a minimum version requirement of 2.12 for QuickCheck.  

This was noted by the stackage folks (https://github.com/hspec/hspec/issues/374) and worked around in https://github.com/commercialhaskell/stackage/commit/f42bab3f708ce31a21d86eae80404ff572de42ef, however the problem still manifests for those of us not using stackage.

Unfortunately, although the comment in that stackage fix stated that hspec-meta is only used by hspec itself, it does block building hspec-discover due to https://github.com/hspec/hspec/blob/master/hspec-discover/hspec-discover.cabal#L85 and hspec-core due to https://github.com/hspec/hspec/blob/master/hspec-core/hspec-core.cabal#L105.

The cabal files in that commit referenced above are updated appropriately... I have no idea where the `hspec-meta.cabal` file is stored (or where the repo is) so I cannot submit a patch to fix this issue, but a cabal unpack reveals a cabal file of that name with the incorrect `QuickCheck >=2.10` internally.

Because I am building packages that have dependencies that have not yet been updated for QuickCheck 2.12, I am constrained to pre-2.12 versions of QuickCheck.  The current workaround is to either use older versions of hspec, or---ironically---disabling tests when building the testing infrastructure.  :-)

The latest hackage versions of the `hspec-core`, `hspec-discover`, and `hspec-meta` packages are all at version 2.6.0, which contains this invalid version constraint.  It would be more convenient if the releases were updated with proper constraints which would make it easier to identify the issue (especially because I can't find hspec-meta.cabal... what am I missing?).

I'm also filing this as a new issue because the original issue (https://github.com/hspec/hspec/issues/374) was filed against version 2.5.6 and the latest release is version 2.6.0, so the problem has existed for at least 5 versioned releases now (perhaps it has been overlooked due to the missing hspec-meta.cabal file?).

**Comment by sol** [comment]
> As I understand it, the version lower bound for `QuickCheck` on `hspec-core` is wrong too. Fixing that would be my primary concern.

Actually you were right, only `hspec-meta-2.6.0` needed updating.  I published a Hackage revision and made sure that the old constraint won't sneak in again in the future (https://github.com/hspec/hspec/commit/29902040039e098894715f70c46c2d93c0a6223a).

**Comment by sol** [comment]
@kquick closing, but please ping me in case you still run into any issues.
