### ISSUE TITLE
line numbers for failures

### ISSUE THREAD

**Issue by gregwebs** [hspec/hspec#4]
Given the descriptive nature of hspec, this is a less pressing concern. Right now one can look at the string for the failure, and find that in the source. However this process could be automated to having hspec report a line number.

HTF provides line numbers by running a pre-processor that replaces assertions with assertions with line numbers. Perhaps that could be used directly. Otherwise, a simpler pre-processor for hspec could could just give line numbers for the 'it' string without figuring out the exact test failure line.

http://hackage.haskell.org/packages/archive/HTF/0.7.0.0/doc/html/Test-Framework-Tutorial.html

**Comment by gregwebs** [comment]
I am adding these functions to the file-location package: http://hackage.haskell.org/package/file-location-0.4.8/docs/Test-FileLocation.html

**Comment by sol** [comment]
:+1:

I still hope we get source locations into GHC soon.

**Comment by sol** [comment]
@gregwebs we have support for source locations on Hackage now.

**Comment by gregwebs** [comment]
fantastic! One more reason I will quickly be upgrading to 7.10.2
