### ISSUE TITLE
Display tests being run

### ISSUE THREAD

**Issue by pepeiborra** [hspec/hspec#402]
As an alternative to reporting slow tests, it would be helpful if specdoc would print the title of the example being run. If parallel execution is enabled, it would be even better to print *all* the tests in execution.

Currently this is not possible using a custom formatter either because there are no "example started" hooks.

**Comment by sol** [comment]
> it would be helpful if specdoc would print the title of the example being run

`hspec-2.7.10` introduced a new formatter that addresses this.  It can be used with `--format checks`.

![`checks` formatter](https://user-images.githubusercontent.com/461132/114891182-dccfe700-9e35-11eb-9435-82fae8ca870b.gif)

**Comment by sol** [comment]
> reporting slow tests

`hspec-2.8.0` adds both `--times` and `--print-slow-items` that should address this request.

> Currently this is not possible using a custom formatter either because there are no "example started" hooks.

`hspec-2.8.0` exposes `Test.Hspec.Core.Format`.  This API is more flexible than what we have in `Test.Hspec.Core.Formatter`.

It reports "started", but only for the next item to be completed.

My apologies for letting #403 bit rot.  If you want to revive it, now would be a good time to do so.

**Comment by sol** [comment]
Related https://github.com/hspec/hspec/pull/405.
