### ISSUE TITLE
Allow arbitrary SpecWith in hspec-discover

### ISSUE THREAD

**Issue by neongreen** [hspec/hspec#404]
We have [a bunch of tests](https://github.com/wireapp/wire-server/tree/develop/services/spar/test-integration/Test/Spar) where each exported spec has the type `SpecWith TestEnv`. It would be nice to use hspec-discover for this test tree, but currently it seems impossible because hspec-discover expectes `spec :: Spec`.

Any advice?

**Comment by sol** [comment]
Yes, this is currently not possible. Would be neat to lift this restriction. Not sure how it will workout, but I think worth a try.

Would you want to give it a try?

**Comment by neongreen** [comment]
My current best idea is "don't generate a signature for the resulting `spec` at all and add an `OPTIONS_GHC` pragma disabling warnings about missing top-level signatures to the resulting file". This way we can also deal with various corner cases like `HasFoo a => SpecWith a` in one file and `HasBar a => SpecWith a` in another file.

Sounds good?

**Comment by sol** [comment]
👍

**Comment by sol** [comment]
Skipping signatures prevents empty test suites from compiling.  This is why I'm not eager to do this by default.  We possibly could hide it behind some cli flag though.

**Comment by sol** [comment]
An other thing that I have been mentally playing around with is this:

If some specific file, say e.g. `Driver.hs` exists, then `hspec-discover` will use it to "post-process" the `spec` with it. Effectively providing an extension point for the user.

So how exactly could that look like?  In the simplest case `Driver.hs` could be something like:

```haskell
-- Driver.hs
import Test.Hspec
driver :: Spec -> IO ()
driver = hspec
```

This is not very useful of course, but a user could plug in all kinds of interesting stuff here, like custom formatters, run additional pre/post IO actions, using `hspecWith` with custom options, etc.

@neongreen I think your specific use case could be covered with something like:

```haskell
driver :: Spec Env -> IO ()
driver = hspec . beforeAll initEnv
```

This can be introduced without much breakage.  However, if an existing user already has some existing `Driver.hs` in his source folder, he would be faced with a compilation error when upgrading `hspec`.  So do we want to make this opt-in with a flag?  Or should we use some more specific module name, e.g. `SpecDriver.hs`?

**Comment by neongreen** [comment]
I've already quit the job where I was intending to use this, so I can't comment much. I can say that `SpecDriver` sounds better than `Driver`, but that's really it.

Maybe @fisx can say something.

**Comment by fisx** [comment]
I'm not sure I understand.  Would the type signature of `driver` determine the types of the `spec` declarations discover should be looking for?  So, if it's `SpecWith Env -> IO ()`, it's looking for `spec :: SpecWith Env`; if it's `Maybe Int`, it'd be looking for that?

It does sound like a good idea, though, like most of your ideas @sol :-P

**Comment by sol** [comment]
`hspec-discover` now looks for `SpecHook.hs` files (top-level and in subdirectories).  A `SpecHook.hs` file is expected to export a `hook`-function that is applied to all specs under the same hierarchy.  This may be suitable for this kind of situation.

Documentation is still pending.  For the time being, look at the example at https://github.com/hspec/hspec/tree/main/hspec-discover/integration-test/with-spec-hook.

**Comment by sol** [comment]
I'm closing this issue, but please feel free to re-open if `SpecHook` does not work for you.

**Comment by fisx** [comment]
Perfect, thanks!
