### ISSUE TITLE
It is not possible to specify exact match when choosing modules to run

### ISSUE THREAD

**Issue by ksvanhorn** [hspec/hspec#407]
I have a project that has modules AST, StanAST, and RAST. Because partial matching is used, there is no way to tell hspec to just run AST, and not the other two.

**Comment by sol** [comment]
Try `-m /AST/`. Does this work for you?

**Comment by ksvanhorn** [comment]
I tried that. It doesn't work -- nothing gets selected. I am using hspec via stack, and I just today downloaded and installed the most recent version of stack, so I would think that had a pretty recent version of hspec.

**Comment by sol** [comment]
Do you see a message like

    To rerun use: --match "..."

for failing spec items? If yes, can you copy & paste one here?

**Comment by ksvanhorn** [comment]
No, I do not.

**Comment by sol** [comment]
I think you are not using the latest version of hspec. If upgrading to the latest version still doesn't solve your use case then please get back here.

**Comment by ksvanhorn** [comment]
I was able to upgrade to a more recent version of hspec by using a more recent resolver, and that solved the problem. Thanks.
