### ISSUE TITLE
Bump version bound for QuickCheck 2.13

### ISSUE THREAD

**Issue by nick8325** [hspec/hspec#410]
I just released QuickCheck 2.13. There are no major API changes and Hspec at least builds with it (I haven't run it) but at least the version bounds will need relaxing.

It also uses `splitmix` rather than `tf-random` for random number generation, which perhaps makes #406 obsolete.

**Comment by sol** [comment]
@nick8325 there seems to be something fishy.

Given
```
ghci> import Test.QuickCheck
ghci> import Test.QuickCheck.Random 
ghci> let p = (/= 1) :: Int -> Bool
ghci> let qc = quickCheckWith stdArgs {replay = Just (mkQCGen 0, 0)}
```

I observe that `verbose` changes the number of tests that are run:

```
ghci> qc p
*** Failed! Falsified (after 6 tests):                      
1
```
vs

```
ghci> qc (verbose p)
...
...
...
*** Failed! Falsified (after 3 tests):                      
1
```

Is this expected?

**Comment by nick8325** [comment]
This is really strange. I hadn't thought about making `verbose p` and `p` behave identically (only that they should have the same distribution of test cases), but of course they should if at all possible.

The weird thing is that this works with `TFGen`, but not with `SMGen` _or_ `StdGen`! Just changing `newTFGen` and `mkTFGen` to `newStdGen` and `mkStdGen` causes your example to break. So it seems that `TFGen` is doing something very strange here. I'll have to look into it more closely.

**Comment by nick8325** [comment]
Oops:

```
import Test.QuickCheck
import System.Random
import System.Random.TF

prop_rng :: Int -> Property
prop_rng n =
  expectFailure $
  genInt g === genInt (fst (split g))
  where
    genInt :: TFGen -> Int
    genInt g = fst (next g)

    g :: TFGen
    g = mkTFGen n

> quickCheck prop_rng 
*** Failed! Passed 100 tests (expected failure).
```

It looks like the problem only occurs with `mkTFGen` and not `newTFGen`.

**Comment by nick8325** [comment]
My initial impression is that this bug shouldn't worsen testing, at least, because a seed in QuickCheck is either split or applied to `next`, never both in the same property.

**Comment by sol** [comment]
@nick8325 there is more.  Apparently `failingTestCase` means something different now.  Consider:

```
ghci> let qc = quickCheckWithResult stdArgs {chatty = False, replay = Just (mkQCGen 0, 0)}
```

With `2.12.6.1`:

```
> failingTestCase <$> qc ((==) :: Int -> Int -> Bool)
["0","1"]
```

vs `2.13`

```
ghci> failingTestCase <$> qc ((==) :: Int -> Int -> Bool)
["1\n0"]
```

**Comment by sol** [comment]
@snoyberg @alexeyzab I can't comment on https://github.com/commercialhaskell/stackage/issues/4444.  `hspec` compatibility with QuickChekc-1.13 will be blocked until we have sorted this stuff out.

**Comment by alexeyzab** [comment]
@sol :+1:

**Comment by nick8325** [comment]
@sol Both of those should be fixed now. Let me know if you're happy for me to make a new release.

**Comment by nick8325** [comment]
Ah wait, not sure that it's working yet. I'll report back...

**Comment by nick8325** [comment]
There, that should be actually fixed now.

**Comment by sol** [comment]
@nick8325 looks good now.  Let me know once it's on Hackage._

**Comment by nick8325** [comment]
There, 2.13.1 is now on Hackage!

**Comment by sol** [comment]
On Hackage, closing.
