### ISSUE TITLE
Enable JUnit XML generation

### ISSUE THREAD

**Issue by eborden** [hspec/hspec#411]
JUnit is a common format for spec reporting. There is a ton of tooling built around generating reports from this format. I have created [a naive `JUnit` formatter](https://github.com/freckle/hspec-junit-formatter). However `Formatter` has a few limitations that make it difficult to produce conforming `JUnit`.

1. `exampleGroupStarted` only tells you the current path, but does not tell you when you are in a leaf group. `JUnit` does not allow nesting of `<testsuite />` elements, so my formatter must create an intermediate format and denormalize all groups into a flat structure. This may be impossible to avoid since, `hspec` groupings can contain more groupings and test cases at the same level.
2. `exampleGroupStarted` does not include a starting time. `JUnit` requires a starting `timestamp` for `<testsuite />` elements.
3. `exampleGroupDone` does not contain timing information. `JUnit` can encode seconds spent in a test suite.
4. `exampleSucceeded`, `exampleFailed`, `examplePending` don't contain timing information. `JUnit` can encode timing for test cases.

`Formatter` is a collection of callbacks that respond to events in the suite. This likely means that an intermediary format cannot be ignore for producing `JUnit`, since it seeks to record summary data. It would be fantastic if `Formatter` was re-thought as a stream of events instead of a collection of callbacks.

```hs
data HspecEvent
  = Started
  | ExampleGroupStarted Path String
  | ExampleGroupDone Path String DiffTime
  | ExampleProgress Path String
  | ExampleSucceeded Path String DiffTime
  | ExampleFailed Path String Reason DiffTime
  | ExamplePending Path String Reason DiffTime
  | Finished Int Int Int DiffTime

type Formatter = Stream HspecEvent -> IO ()
```

That lifts some limitations that are currently enforced by a custom `Monad` and rigid structure. It also provides a backwards compatible path that old formatters and existing functions can work within.

**Comment by sol** [comment]
We now have `Test.Hspec.Core.Format` which I hope is flexible enough to cover this use case.
