### ISSUE TITLE
afterAll couldn't call cleanup code when interrupted by signal.

### ISSUE THREAD

**Issue by cutsea110** [hspec/hspec#424]
The cleanup code is called by ```afterAll```, but the cleanup code is not called when interrupted by **C-c**.
It seems that after is finally and action is called, but ```afterAll``` does not. Can't make sure cleanup code is called in finally?

**Comment by sol** [comment]
@cutsea110 in general, it's not a good idea to rely on `finally` and friends to cleanup out-of-process resources.  Your process could always get killed with `SIGKILL`.

That said, not sure if there is something that can be done, but if you see a way to make the current code more robust I'm open for a PR.

NB: Doing your "cleanup" a `beforeAll` to cleanup stuff from previous test runs is a common workaround for this kind of problems.

Closing.
