### ISSUE TITLE
hspec perfomance and SpecM

### ISSUE THREAD

**Issue by Hexirp** [hspec/hspec#425]
I am grateful for the hspec project. That DSL is cool.

But I have one thing to worry about.

https://github.com/hspec/hspec/blob/9f3f4c38952f526701a67b6e26336a3a5aec0e89/hspec-core/src/Test/Hspec/Core/Spec/Monad.hs#L28-L31

It seems to be inefficient. O(n^2) is really bad. I know HUnit is much faster than hspec. I think the reason lies in the definition of SpecM.

I suggest using DList or Seq. But there may be difficulties I don't know. Sorry if you feel bad!

**Comment by sol** [comment]
> I know HUnit is much faster than hspec.

I would be very surprised if this is indeed the case.  Do you have any numbers to backup this claim?

**Comment by Hexirp** [comment]
I don’t remember what my rationale was at the time. I close this issue now. Thank you.
