### ISSUE TITLE
Trouble using HSpec with quickcheck-classes

### ISSUE THREAD

**Issue by kozross** [hspec/hspec#427]
I attempted to combine the functionality of [quickcheck-classes][1] and HSpec, mostly by following [the guide for integrating QuickCheck][2]. The code I ended up with looked as so:

```haskell
main :: IO ()
main = hspec jsonSpec

jsonSpec :: Spec
jsonSpec = describe "JSON round-tripping". fromLaws $ laws
    where laws = jsonLaws (Proxy @Foo)
               fromLaws (Laws _ props) = traverse_ (\(name, prop) -> it name prop) props
```

The ``Foo`` type is a fairly standard sum, whose ``Arbitrary`` instance basically generates a random ``Int`` and picks a constructor on that basis. However, when I ran this, the following unexpected things happened:

1) There was no feedback about what caused a failure of this test; and
2) A memory leak happened (exhausting 64G of RAM).

This was written against the versions of both HSpec and quickcheck-classes in LTS-14.17 (2.7.1 and 0.6.1.0). Is this a bug, or am I not using HSpec and quickcheck-classes together properly?

[1]: https://hackage.haskell.org/package/quickcheck-classes
[2]: http://hspec.github.io/quickcheck.html

**Comment by kozross** [comment]
Seems the issue was on my end - I was accidentally causing big generator loops. It would still be nice to have integration between HSpec and quickcheck-classes.

**Comment by sol** [comment]
Hey! Glad you figured things out!

> It would still be nice to have integration between HSpec and quickcheck-classes.

I think this could be an opportunity for a thing party project.  If you happen to tackle it, I would be happy to link to it from the Hspec docs.

**Comment by jonathanknowles** [comment]
@sol @kozross 

Regarding an integration between `Hspec` and `quickcheck-classes`, I've been using the following functions (copied and pasted!) in many of my projects:

- [`testLaws`](https://github.com/jonathanknowles/taiwan-id/blob/cbc9e2e55226b3cb9b9190f03e33cc603fe038dc/components/test/taiwan-id-test/Test/QuickCheck/Classes/Hspec.hs#L33)
- [`testLawsMany`](https://github.com/jonathanknowles/taiwan-id/blob/cbc9e2e55226b3cb9b9190f03e33cc603fe038dc/components/test/taiwan-id-test/Test/QuickCheck/Classes/Hspec.hs#L60)

Notably, these functions are kind-polymorphic. So for example, they work equally well with `semigroupLaws` and `functorLaws`, even though those law sets target different kinds (`Type` and `Type -> Type` respectively).

Here are some examples of `testLawsMany` in action:

- https://github.com/jonathanknowles/taiwan-id/blob/cbc9e2e55226b3cb9b9190f03e33cc603fe038dc/components/test/taiwan-id-test/Main.hs#L97

- https://github.com/jonathanknowles/monoidmap-internal/blob/dded2d1119e746b5a61acba71b49f3d9abf8155c/components/monoidmap-test/Data/MonoidMap/Internal/RecoveredMapSpec.hs#L107

Would a solution like this work for you?

I was actually planning to extract this out into a separate package (to avoid copying and pasting it all over the place). Would be interested in any feedback you may have!
