### ISSUE TITLE
modifyMaxSize appears to have no effect

### ISSUE THREAD

**Issue by kozross** [hspec/hspec#428]
I have code as follows:

```haskell
main :: IO ()
main = hspec jsonSpec

jsonSpec :: Spec
jsonSpec = describe "JSON round-tripping" . fromLaws $ laws
  where laws = jsonLaws (Proxy @Foo)

fromLaws :: Laws -> Spec
fromLaws (Laws _ props) = traverse_ go props
  where go (name, prop) = it name prop
```

I've tried [following this guide here][1] to increase the number of maximum successes (by adding ``modifyMaxSize (const 1000)``), but no matter where I put it, it doesn't seem to have any effect. Where should it go in this case?

[1]: http://hspec.github.io/quickcheck.html

**Comment by sol** [comment]
Use `modifyMaxSuccess` instead of `modifyMaxSize`.
