### ISSUE TITLE
Update `options` docs to reflect `cabal v2-` changes

### ISSUE THREAD

**Issue by harpocrates** [hspec/hspec#430]
In `cabal v2-test` (which is also now the default for `cabal test`), the `--show-details` option is renamed to `--test-show-details`. Perhaps this could be clarified in https://github.com/hspec/hspec/blob/master/doc/options.md? Cabal's default for this option is indeed pretty unfortunate.

Thanks for the great project!

**Comment by sol** [comment]
Hey! Thanks for bringing this up and sorry for the delay!

Done!
