### ISSUE TITLE
Option to redirect / suppress stderr

### ISSUE THREAD

**Issue by ad-si** [hspec/hspec#435]
In your example in the documentation
```hs
launchMissiles `shouldThrow` (== ExitFailure 1)
```
`launchMissiles` is probably going to write to stderr.
However, there is currently no way to capture / redirect the output to stderr, right?
This means it will be printed to the terminal between the desired hspec tests and mess up the test  report.
Is there any solution to this problem?

**Comment by sol** [comment]
I guess you could make the point that it's cleaner to avoid writing to `stdout` (or `stderr`) directly and instead let the caller decide where output goes.

However, if this is impractical, take a look at https://hackage.haskell.org/package/silently.
