### ISSUE TITLE
Add a --parallel option to hspec-discover

### ISSUE THREAD

**Issue by seagreen** [hspec/hspec#437]
I really like `hspec-discover`, but it runs everything sequentially so I can't use it for big projects.

Interestingly, this idea got mentioned 7(!) years ago: https://github.com/hspec/hspec/issues/104#issuecomment-19154667

**Comment by seagreen** [comment]
Oooh, I actually see how to do this.

You use the "Custom main function" strategy from here: http://hspec.github.io/hspec-discover.html#using-a-custom-main-function

... and then wrap the `spec` with `parallel`.

I think that takes care of this issue, at least for me.

**Comment by sol** [comment]
[Spec hooks](https://hspec.github.io/hspec-discover.html#spec-hooks) are easier to use than a custom main function:
```haskell
-- file test/SpecHook.hs
module SpecHook where

import           Test.Hspec

hook :: Spec -> Spec
hook = parallel
```

I think we explicitly want to mention in the docs how to use spec hooks to mark all spec items for parallel execution.

**Comment by sol** [comment]
https://hspec.github.io/parallel-spec-execution.html#running-all-tests-in-parallel-with-hspec-discover
