### ISSUE TITLE
Add analogue of describe.each/test.each from Jest

### ISSUE THREAD

**Issue by Jazzmanpw** [hspec/hspec#448]
I came to Haskell from JS, and in the Jest library there are convenient functions to write similar tests:
```js
test.each([
  [/abc/, 'abcdef', 'abc'],
  [/ba[rz]/, 'barrel', 'bar'],
])('regex matches string', (regex, source, expected) => {
  expect(source.match(regex)[0]).toBe(expected);
});
```
It might be convenient to have similar tools. I couldn't find anything like that in the Haskell testing libraries either.

**Comment by sol** [comment]
@Jazzmanpw hey! Thanks for opening this issue!

Have you tried something along those lines:
```haskell
module RegexSpec (spec) where

import           Test.Hspec
import           Control.Monad

spec :: Spec
spec = do
  forM_ [
      ("/abc/", "abcdef", "abc")
    , ("/ba[rz]/", "barrel", "bar")
    ] $ \ (regex, source, expected) -> do
      it (regex <> " matches " <> source) $ do
        (regex `matches` source) `shouldBe` expected
```
Does `test.each` offer any substantial improvements over this?

**Comment by Jazzmanpw** [comment]
It looks just like what I wanted! Thanks for the answer!
I think it should be added to the documentation as a possible way to do this. Newcomers like me would appreciate it a lot, I believe.

**Comment by sol** [comment]
@Jazzmanpw you are welcome!

>  I think it should be added to the documentation as a possible way to do this. Newcomers like me would appreciate it a lot, I believe.
I agree that this could be useful, however, teaching general Haskell idioms is outside the scope of Hspec's docs.
