### ISSUE TITLE
Interweave steps in state monad and hspec tests

### ISSUE THREAD

**Issue by habbler** [hspec/hspec#478]
Hello, 
I want to carry out steps in a state monad, and after each step carry out different tests.
So I either need to embed the state monad in the hspec monad or the other way around.

The best way I have found so far is:

testH01 :: StateT MState (SpecM ()) ()
testH01 = do put tstDelivery_PO1 { stCurrentTime = Time 3 }
             hoistState $ applyPO tdPO2 >> procPendingMM  
             lift $ describe "afsdfd" $ return ()

However this requires accessing SpecM from the hspec-core package.
Is there anyway of doing this without accessing the internals of hspec ? (SpecM).

I guess one way would to be just not to give a type signature... as SpecM () is implied anyway. But I like giving top level type signatures.

**Comment by sol** [comment]
@habbler There are no issues with accessing things from `hspec-core`.  However, `SpecM` is a monad that constructs a test tree.  What ever you do there will be executed before any tests are run.  So it will not be interleaved with your tests or something.  I'm saying this just in case this is what you are trying to do.

If you can provide more insights in what you are trying to do I might be able to steer you in the right direction.

**Comment by habbler** [comment]
@sol Thanks for the info.
Note that the interleaving works fine. What counts is when the tests are constructed. i.e. the test thunks capture the state of the statement monad as it executes. (the expected values).

Solved the problem of not using SpecM by calling runStateT within my function. Then the resulting function just has type Spec.

testH01 :: Spec
testH01 = flip evalStateT tstStart $ do
             let tdPO1 = createPO (Time 1) (MatNr 2) (MatAmt 2) tstStart
             po1 <- h $ applyPO tdPO1
             assertEq "openMatTran po1" (S.elemAt 0 <$> use openMatTran) $ head expMatTransFinal
             
             currentTime .= Time 2

 where h = hoistState
        assertEq msg act exp1 = do val <- act
                                   lift $ it msg $ val `shouldBe` exp1
