### ISSUE TITLE
Hspec.sequential runs spec items backwards

### ISSUE THREAD

**Issue by codygman** [hspec/hspec#482]
```haskell
describe $ parallel $ 
     -- other items to run in parallel here
     sequential $ do
        it "sequential item 1" $ do
            putStrLn "sequential item 1"
        it "sequential item 2" $ do
            putStrLn "sequential item 2"
```

It seems that after 10 runs sequential item 2 always runs first.

**Comment by sol** [comment]
@codygman thanks for opening this.  If you want me to look into this I'll need the following:

- A full self-contained code example that demonstrates the unexpected behavior.
- A short description of what behavior you expected.
- A short description of what behavior you observed.
