### ISSUE TITLE
How to run some tests sequentially?

### ISSUE THREAD

**Issue by JivanRoquet** [hspec/hspec#533]
The following example uses `H.sequential` within a test suite:

```haskell
import           Test.Hspec
import qualified Test.Hspec.Core.Spec    as H

spec :: Spec
spec =
    describe "foo" $ do

        H.sequential $ it "thirtyTwo" $ do
            30 + 2 `shouldBe` 32

        H.sequential $ it "thirtyFive" $ do
            40 - 5 `shouldBe` 35
```

However, I can observe that `thirtyTwo` and `thirtyFive` run concurrently.

Am I missing something here? How can we make sure that `thirtyFive` runs only when `thirtyTwo` has already completed?

**Comment by JivanRoquet** [comment]
See also issue #438

**Comment by sol** [comment]
> However, I can observe that `thirtyTwo` and `thirtyFive` run concurrently.

How exactly did you observe this?

Without using `parallel` anywhere is your test suit, `hspec` will not run any tests in parallel.  If you still observe something unexpected, can you please provide an example that reproduces the issue?
