### ISSUE TITLE
How/whether to contribute code regarding shouldMatch

### ISSUE THREAD

**Issue by chrisdone** [hspec/hspec#534]
Hi, I made a small gist demonstrating a way of expressing `shouldBe` that is really a `shouldMatch` where parts of the data can have "holes" - those that aren't relevant for a test:

https://gist.github.com/chrisdone/657b6544235c111949e19dde366aa4dc

Presently, I'm just using `shouldSatisfy` as shown in the Gist. The downside of this is when the match fails, you just get "didn't match" but no diff to tell you where.

So, I'd like to make a `shouldMatch` that might look like:

```haskell
it
  "Ints"
  (shouldMatch
     (guessCsvSchema (File {id = 0, name = ""}) "int\n1\n2")
     $(pat
         [|CsvGuessed
             (CsvImportSpec
                { columns =
                    [ CsvColumn
                        { action =
                            ImportAction
                              (ImportColumn
                                 { importType =
                                     IntegerType (Required _)
                                 })
                        }
                    ]
                })|]))
```

Where `pat` (or some other name) would produce a function producing a structured coloured diff, with the extraneous fields omitted. 

I could put this in a package like `hspec-match`, or submit it for `hspec-expectations` under `Test.Hspec.Expectations` or even `Test.Hspec.Expectations.TH`. Any preference?

**Comment by sol** [comment]
Hey, that's a creative approach!  I would be eager to experiment with it!

- `hspec` currently does not allow to extend diffing or colorization (something that would be neat to address, e.g. `hspec-wai` could benefit from it too).
- `template-haskell` / `ghci` is not always available, if we add it to `hspec-expectations` I think we would need to make it optional.
- I think having a separate package `hspec-match` is the fastest way to get something out to experiment with. 
- If you want to add a repo for `hspec-match` to the `hspec` GitHub org than I'm more than happy with that (I sent you an invite).
- Right now I have some mild relapse / discomfort in my hands.  This is why I make any commitments.  But if you need any changes to `hspec` (e.g. for color support) I'll try to look at them.

Some questions regarding your comment

> Why from Exp instead of Pat? Because hindent and structured-haskell-mode handle it better.

- Does it technically indeed work to change the type of `match` to `Q Pat -> Q Exp` and as a result force the anonymous Haskell quasi-quoter to produce a pattern (say using `quotePat`)? Or what exactly do you refer to?
- Assuming the answer to my first question is "yes", then how does e.g. `hindent` observe the difference?  The concrete syntax should be the same, or does `hindent` do something more clever?

**Comment by chrisdone** [comment]
Thanks! I'll go with `hspec-match` so I can experiment when I start this.

For a Proper(tm) library, using the built-in `[p|..|]` syntax (pattern quotes) is the right way. That gives you a `Q Pat`.

hindent just indents this with haskell-src-ext's default (bad) printer, so hindent needs to be updated before I can personally get joy out of `[p|..|]`. I'll check up on that before proceeding. It might be a simple update. 

I checked SHM and it's actually OK with `[p|..|]`. 

Regarding QQ's, with a `QuasiQuote` you have to implement the parser yourself (e.g. via ghc-api or HSE), and pretty printers/editors won't be able to manipulate the contents of the `[foo|...|]`. So I generally go for `$(foo [| .. |])` over `[foo|...|]` because my editor can format and navigate the former, but the latter is an opaque string. Having both options can also be fine.
