### ISSUE TITLE
An option for hspec-discover to use a custom prefix or a pattern for locating specs

### ISSUE THREAD

**Issue by oshyshko** [hspec/hspec#535]
As a programmer and hspec/hspec-discover user I want to have a way to specify that spec files are named with "Spec" prefix rather than suffix.

For example, this could be `--use-prefix` option to `hspec-discover`.

`{-# OPTIONS_GHC -F -pgmF hspec-discover -optF --use-prefix=Spec #-}`

Or, even better, `--spec-pattern`:

`{-# OPTIONS_GHC -F -pgmF hspec-discover -optF --spec-pattern="**/Spec*.hs" #-}`

Motivation:

There are projects that use prefix naming such as `SpecModule1.hs`, `SpecModule2.hs`
or`TestModule1.hs`, `TestModule2.hs` instead of default naming hspec expects.

Why: when developer uses an IDE and looks up a module using incremental file search, he types: "Mod" and sees:
- Module1.hs
- Module2Spec.hs
- Module1.hs
- Module2Spec.hs

The results are polluted with tests. Imagine this for projects with many files. 50% of your search results is polluted in tis way.

With prefix naming, a developer can quickly specify, what to he wants to find, implementation or tests:

Typing "Mo" gives:
- Module1.hs
- Module1.hs

Typing "Sp" gives
- SpecModule1.hs
- SpecModule2.hs

**Comment by sol** [comment]
This is outside the scope of `hspec-discover`, so it's not going to happen.

I still think `--spec-pattern` could be neat.

Anybody, please feel free to create a friendly fork of `hspec-discover` (e.g. call it `hspec-discovery` with that trailing `y`) that adds more features.

This should be easy to implement by e.g. using the `Glob` package (which I'm not eager to add as a dependency to `hspec` proper).  I'm also open to export more stuff from `hspec-discover` (the library) if that will be helpful for a third-party discovery tool.
