### ISSUE TITLE
Background threads don't die when test suite killed

### ISSUE THREAD

**Issue by treeowl** [hspec/hspec#537]
I've been using hspec with hedgehog. When a poorly sized test takes too much time and/or memory, I hit Ctrl-C. This immediately drops me to the command line, which is nice. Unfortunately, it leaves the misbehaving thread running in the background, and I end up having to kill it manually! I don't know if the issue is with hspec, or hedgehog, or hspec-hedgehog, but I'd love to see it fixed!

**Comment by sol** [comment]
@treeowl can you provide exact steps on how to reproduce the issue.

If it is reproducible using `hspec` alone then I'm happy to provide a fix, otherwise it might make sense to open an issue against `hspec-hedgehog`.

**Comment by sol** [comment]
Without a repro I'm not going to look into his.  I'm closing this issue.  Please feel free to open a new issue with exact steps on how to reproduce.

**Comment by treeowl** [comment]
Sorry, I lost track of this, and don't remember what I was working on at the time.
