### ISSUE TITLE
hspec-core-2.9.1 compilation error with GHC-7.4

### ISSUE THREAD

**Issue by phadej** [hspec/hspec#576]
```
Building library for hspec-core-2.9.1..
[ 9 of 37] Compiling Text.Show.Unicode ( vendor/Text/Show/Unicode.hs, /codetmp/hspec/hspec-core-2.9.1/.dist-newstyle-trustee/b2ac2370c30c8fc4dd4f1b77c0284c067f110bb3d00afbd629b4aecc2862a15c6b9f5233397c106c774760b16c72e735a412897524a82b442d17b1b878bb33e5/build/x86_64-linux/ghc-7.4.2/hspec-core-2.9.1/noopt/build/Text/Show/Unicode.o )


vendor/Text/Show/Unicode.hs:86:36:
    No instance for (Applicative ReadP)
      arising from a use of `<*'
    Possible fix: add an instance declaration for (Applicative ReadP)
    In the expression: lexChar <* consumeEmpties
    In an equation for `lexCharAndConsumeEmpties':
        lexCharAndConsumeEmpties
          = lexChar <* consumeEmpties
          where
              consumeEmpties :: ReadP ()
              consumeEmpties
                = do { rest <- look;
                       .... }
```

I made a revision: https://hackage.haskell.org/package/hspec-core-2.9.1/revisions/

**Comment by sol** [comment]
@phadej thanks for reporting.

I'm puzzled why CI didn't catch this.  Looking into it now.

**Comment by sol** [comment]
The root cause of the issue is that `hashable-1.4.0.0` depends on `base-orphans`.  So you will end up with the instance depending on which version of `hashable` is chosen.  This is the reason why it works on CI, but not when installed from Hackage.

Not too excited.

@phadej do you know of a way to get a dependency graph for new-build / GHC env file dependencies?  Similar to what we had with `ghc-pkg dot`?

**Comment by sol** [comment]
- `stm` depends on `nats`
- `nats` depends on `hashable`
- `hashable` depends on:
  ```
  base-orphans 
  functor-classes-compat
  ghc-bignum-orphans
  transformers-compat
  ```
@RyanGlScott @phadej can I get your perspective on this?

**Comment by sol** [comment]
@RyanGlScott @phadej an other issue with this is that it introduces a cyclic dependency for the test suite of `base-orphans`.

**Comment by RyanGlScott** [comment]
Indeed, the `Applicative` instance for `ReadP` wasn't introduced until GHC 7.6. If you wish to continue supporting GHC 7.4, some possible solutions could be:

1. Use `ReadP`'s `Monad` instance instead of its `Applicative` instance, or
2. Make `hspec-core` always import `Data.Orphans` to ensure that the `Applicative ReadP` instance is always in scope.

I don't have a strong opinion on which approach to use. I'm actually not able to reproduce the cyclic dependency in the `base-orphans`' test suite that you observed, even if I add a dependency on a library that explicitly depends on `base-orphans`. But even if there is a cyclic dependency, I'm not too worried. It's quite possible to move `base-orphans`' test suite to another `.cabal` file so that dependency cycles aren't an issue. (To be honest, I'm surprised that I haven't had to do so already, given how popular `base-orphans` has become.)

**Comment by sol** [comment]
@RyanGlScott my issue is not so much how to technically fix this (using `ap` instead of `<*>` is easy).  The issue is that it doesn't fail on CI.

**Comment by RyanGlScott** [comment]
OK. I'm not a `hashable` maintainer, so I can't speak much to that side of things. I'm happy to make whatever changes are necessary on `base-orphans`' end, of course.

**Comment by phadej** [comment]
> The issue is that it doesn't fail on CI.

Looks like that is an issue with CI. Locally:

```
% cabal build hspec-core -w ghc-7.4.2
Resolving dependencies...
Build profile: -w ghc-7.4.2 -O1
In order, the following will be built (use -v for more details):
 - hspec-core-2.9.1 (lib) (first run)
Configuring library for hspec-core-2.9.1..
Preprocessing library for hspec-core-2.9.1..
Building library for hspec-core-2.9.1..
[ 1 of 37] Compiling Paths_hspec_core ( /codetmp/hspec/dist-newstyle/build/x86_64-linux/ghc-7.4.2/hspec-core-2.9.1/build/autogen/Paths_hspec_core.hs, /codetmp/hspec/dist-newstyle/build/x86_64-linux/ghc-7.4.2/hspec-core-2.9.1/build/Paths_hspec_core.o )
[ 2 of 37] Compiling Data.Algorithm.Diff ( vendor/Data/Algorithm/Diff.hs, /codetmp/hspec/dist-newstyle/build/x86_64-linux/ghc-7.4.2/hspec-core-2.9.1/build/Data/Algorithm/Diff.o )
[ 3 of 37] Compiling Control.Concurrent.Async ( vendor/Control/Concurrent/Async.hs, /codetmp/hspec/dist-newstyle/build/x86_64-linux/ghc-7.4.2/hspec-core-2.9.1/build/Control/Concurrent/Async.o )
[ 4 of 37] Compiling Test.Hspec.Core.Compat ( src/Test/Hspec/Core/Compat.hs, /codetmp/hspec/dist-newstyle/build/x86_64-linux/ghc-7.4.2/hspec-core-2.9.1/build/Test/Hspec/Core/Compat.o )
[ 5 of 37] Compiling Test.Hspec.Core.Util ( src/Test/Hspec/Core/Util.hs, /codetmp/hspec/dist-newstyle/build/x86_64-linux/ghc-7.4.2/hspec-core-2.9.1/build/Test/Hspec/Core/Util.o )
[ 6 of 37] Compiling Test.Hspec.Core.QuickCheckUtil ( src/Test/Hspec/Core/QuickCheckUtil.hs, /codetmp/hspec/dist-newstyle/build/x86_64-linux/ghc-7.4.2/hspec-core-2.9.1/build/Test/Hspec/Core/QuickCheckUtil.o )
[ 7 of 37] Compiling Test.Hspec.Core.Clock ( src/Test/Hspec/Core/Clock.hs, /codetmp/hspec/dist-newstyle/build/x86_64-linux/ghc-7.4.2/hspec-core-2.9.1/build/Test/Hspec/Core/Clock.o )
[ 8 of 37] Compiling Test.Hspec.Core.Formatters.Diff ( src/Test/Hspec/Core/Formatters/Diff.hs, /codetmp/hspec/dist-newstyle/build/x86_64-linux/ghc-7.4.2/hspec-core-2.9.1/build/Test/Hspec/Core/Formatters/Diff.o )
[ 9 of 37] Compiling Text.Show.Unicode ( vendor/Text/Show/Unicode.hs, /codetmp/hspec/dist-newstyle/build/x86_64-linux/ghc-7.4.2/hspec-core-2.9.1/build/Text/Show/Unicode.o )

vendor/Text/Show/Unicode.hs:86:36:
    No instance for (Applicative ReadP)
      arising from a use of `<*'
    Possible fix: add an instance declaration for (Applicative ReadP)
    In the expression: lexChar <* consumeEmpties
    In an equation for `lexCharAndConsumeEmpties':
        lexCharAndConsumeEmpties
          = lexChar <* consumeEmpties
          where
              consumeEmpties :: ReadP ()
              consumeEmpties
                = do { rest <- look;
                       .... }
```

I also made a fork with `haskell-ci` CI, and that failed as well:

https://github.com/phadej/hspec/runs/4253852040

See `dump install plan` step for dependencies.

**Comment by phadej** [comment]
It seems that we are hitting some bug in GHC, because if I do:

```
cabal build -w ghc-7.4.2 -- fails
cabal build -w ghc-7.4.2 --constraint=transformers==0.3.0.0 -- succeeds
cabal build -w ghc-7.4.2 -- succeeds
```

IIRC there was some bugs that orphans leak even they are not imported directly. Maybe @RyanGlScott remembers better.

**Comment by sol** [comment]
Ok, so from what I understand there are three things that contribute to this this situation (CI passing, even it shouldn't):

1. `hashable-1.4.0.0` having a somewhat heavy dependency footprint (including `base-orphans`)
2. `cabal` select different install plans with/without `--enable-tests`
3. A GHC bug that leaks instance into `Text.Show.Unicode` even though `Text.Show.Unicode` only importing stuff from `base` (directly or indirectly)

If (3) is the case, that would restore some of my sanity.  But nothing that we can fix.

(2) is something we have to live with as well.

As for (1).  What is the reason that `hashable` is a separate package from `unordered-containers`?

**Comment by phadej** [comment]
> But nothing that we can fix.

I'd suggest `hspec-core` to depend oon `base-orphans` and import it. That is a fix.

**Comment by sol** [comment]
> As for (1). What is the reason that `hashable` is a separate package from `unordered-containers`?

To answer my own question: As I understand it, the idea was that `hashable` has minimal dependencies so that other packages can depend on it and provide `Hashable` instances without pulling in unnecessary dependencies.

@phadej any chance we can address this in `hashable`?

**Comment by phadej** [comment]
I don't understand. What you think is wrong with `hashable`?

AFAICT `hashable` has as minimal dependencies as it can have (only boot libraries with latest GHC), but on older GHCs it has to depend on compatibility packages. (see https://hackage.haskell.org/package/hashable-1.4.0.0/dependencies)

**Comment by sol** [comment]
@phadej for what it's worth, depending on `base-orphans` conditionally is worse than depending on it unconditionally.  In this specific case it doesn't matter (yet) because it's only the latest version of GHC that is excluded.  Do you understand what I mean with "worse"?  What's the reason you make that dependency conditional?

**Comment by phadej** [comment]
I can make it unconditional too. That change won't solve this issue.

**Comment by sol** [comment]
@phadej the bug is that it did not fail no CI, so a broken version ended up on Hackage.  Without `hashable-1.4` it would have failed on CI and never ended up on `main`.

**Comment by sol** [comment]
@phadej to be clear, I'm happy that you reported the issue.  That is immensely helpful.  So please do that in the future.

What I'm not excited about is that CI did not catch the error.  That is not your fault.

Regarding `hashable-1.4.0.0`, I think the change is to invasive (it has 955 direct dependencies, and probably many, many more indirect dependencies).  I'm not per se concerned about `base-orphans`.  But I think `hashable` is too deep down the stack.  That's my opinion. Your your mileage may vary.

#580 solves the imminent issue, but it does not ensure that it won't happen again.  I'm still undecided how to address this.

**Comment by phadej** [comment]
It's hard to exhaustively check for all possible install plans. These kind of issues happen, and I wouldn't stress too much about them. (unlucky combination of GHC bug and particular dependency structure).
