### ISSUE TITLE
Add a way to get ancestor test group path in SpecM

### ISSUE THREAD

**Issue by srid** [hspec/hspec#637]
```haskell
newtype SpecM a r = SpecM (WriterT (Endo Config, [SpecTree a]) (ReaderT Env IO) r)
  deriving (Functor, Applicative, Monad)
```

This adds an `Env` that stores the "current" test group ancestor that can be retrieved in any `describe` block:

```haskell
-- | Environment of a test definition, in the Spec monad
data Env = Env 
  { envAncestorGroups :: [String]  -- Should this be non empty?
  }
  deriving (Eq, Show, Ord)

askAncestors :: SpecM a [String]
askAncestors = do 
  SpecM $ lift $ asks envAncestorGroups
```

I need `askAncestors` in order to determine the paths to golden files. The idea is to determine this path automatically depending on where in the test hierarchy one is.

---

Is this the right approach to solve this? I can open a PR.

**Comment by srid** [comment]
Where `Env` is modified:

```haskell
mapSpecForest_ :: (Env -> Env) -> ([SpecTree a] -> [SpecTree b]) -> SpecM a r -> SpecM b r
mapSpecForest_ ef tf (SpecM specs) = SpecM $ flip mapWriterT specs $ 
  mapReaderT (fmap (fmap (second tf))) . withReaderT ef

describe :: HasCallStack => String -> SpecWith a -> SpecWith a
describe label = mapSpecForest_ (\(Env ancs) -> Env $ label : ancs) (return . specGroup label)
```

**Comment by srid** [comment]
This would be analogous to sydtest's `getTestDescriptionPath`,
- https://github.com/Plutonomicon/plutarch/blob/a4541a3100e27558485082aabe2e90bff9e125b8/plutarch-test/common/Plutarch/Test/Golden.hs#L138-L140

**Comment by srid** [comment]
I suppose I can do this outside of `hspec`, by wrapping the original monad:

```haskell
{- | Like `SpecM`, but leaves a trail from root node, allowing retrieval of
 ancestor path from anywhere in the test hierarchy. See `getTrail`.

 When using this to define your test hierarchy, you ought to use `describe` to
 group sub-trees. Use `lift` to drop-down into the underlying `SpecM` monad.

 m ~ SpecM a
-}
newtype TrailSpecM m r = TrailSpecM (ReaderT [String] m r)
  deriving newtype (Functor, Applicative, Monad, MonadTrans)
```

**Comment by sol** [comment]
@srid I still think this is a reasonable request. The only thing I'm concerned about is backwards compat (I'm actually considering to revert/defer https://github.com/hspec/hspec/commit/a4ecac2a0fec73a44d8886c86000a2684d183b97 for that very reason) that's why I wouldn't want to rush it.

**Comment by srid** [comment]
Okay. Here's what I had in mind, FWIW: https://github.com/Plutonomicon/plutarch/commit/fd84c3d6bf6d3035aaec84aab5ea0ebea62d7a45

**Comment by srid** [comment]
> revert/defer https://github.com/hspec/hspec/commit/a4ecac2a0fec73a44d8886c86000a2684d183b97 for that very reason

Out of curiosity, what was the specific use case for that feature (`modifyConfig`)?

**Comment by sol** [comment]
> > revert/defer [a4ecac2](https://github.com/hspec/hspec/commit/a4ecac2a0fec73a44d8886c86000a2684d183b97) for that very reason
> 
> Out of curiosity, what was the specific use case for that feature (`modifyConfig`)?

To register a formatter in `SpecHook.hs`, e.g.:

```haskell
import Test.Hspec
import qualified MyFancyFormat

hook :: Spec -> Spec
hook = MyFancyFormat.register
```

**Comment by sol** [comment]
https://github.com/hspec/hspec/pull/527 is an alternative (`hspec-discover` only) approach that does not introduce breaking changes.

**Comment by sol** [comment]
@srid I temporarily reverted a4ecac2 so that I could cut an other minor release, `2.9.5`.

But it will land in `2.10.0`.

Now is a good time to add this.


> Is this the right approach to solve this?

Yes, `ReaderT` / `local` looks sensible.

> I can open a PR.

Yes, please! Base your changes on #641 / https://github.com/hspec/hspec/tree/transform-config.

**Comment by srid** [comment]
@sol Looks like that branch got merged to `main`; Here's the PR you requested: #648
