### ISSUE TITLE
A way to get the test tree after test run

### ISSUE THREAD

**Issue by srid** [hspec/hspec#649]
I notice that `hspecResult` returns a `Summary` of the test run. Can this `Summary` be made to include the test forest[^req] as well?

Failing that, maybe: 
```haskell
hspecWithResultAndForest :: Config -> Spec -> IO (Summary, [SpecTree ()])
```

[^req]: Here's a specific use case: I'd like to accumulate all golden files touched by a test run, assuming that the [`goldenFile`](https://hackage.haskell.org/package/hspec-golden-0.2.0.0/docs/Test-Hspec-Golden.html) path was determined from `askAncestors` of #648 (see the `sydtest` analogue [here](https://github.com/Plutonomicon/plutarch/blob/9a173e605fa0bbd66010e33e79e376602d0a8b6d/plutarch-test/common/Plutarch/Test/Run.hs#L73-L80)). More generally, we can do other sorts of post-processing on the tree.

**Comment by sol** [comment]
Changing `hspecResult` would be a breaking change, but we can change `runSpecForest` as it hasn't been released yet.

**Comment by srid** [comment]
Unless you meant changing `runSpecForest` to be like `hspecForest` in the diff above?

**Comment by srid** [comment]
@sol I don't understand that PR. How can I get a `[SpecTree ()]` at the end of a test run? Presently, I do this:

```haskell
main = do 
  hspec spec -- Run tests
  checkUnusedGoldens . snd <$> runSpecM spec -- Check for unused goldens and fail
```

- https://github.com/Plutonomicon/plutarch/blob/4052b285eb890799332c0cbe19cb08c1070f267a/plutarch-test/Main.hs#L22
- https://github.com/Plutonomicon/plutarch/blob/4052b285eb890799332c0cbe19cb08c1070f267a/plutarch-test/common/Plutarch/Test/Run.hs#L26

The only reason for the `runSpecM spec` is because the former expression, `hspec spec`, doesn't return the test tree (what this issue is about).

How can #656 be used to implement this? I don't even see a reference to `SpecTree` in there.

**Comment by srid** [comment]
More precisely,

```haskell
hspecAndReturnForest spec =
  hspec spec >> fmap snd (runSpecM spec)
```

Can this function be implemented without evaluating the `spec` twice?

**Comment by sol** [comment]
Let's look at the default definition of `hspec`:
```haskell
hspec :: Spec -> IO ()
hspec = evalSpec defaultConfig >=> \ (config, spec) ->
      getArgs
  >>= readConfig config
  >>= withArgs [] . runSpecForest spec
  >>= evaluateResult
```
An other way to write this is:
```haskell
hspec :: Spec -> IO ()
hspec spec0 = do
  (config, spec) <- evalSpec defaultConfig spec0
  result <- getArgs >>= readConfig config >>= withArgs [] . runSpecForest spec
  evaluateResult result
```

If you want to operate on the unevaluated spec forest, I think you can do that already:

```haskell
hspecAndCheckUnusedGoldens :: Spec -> IO ()
hspecAndCheckUnusedGoldens spec0 = do
  ...
  checkUnusedGoldens spec
  evaluateResult result

checkUnusedGoldens :: [SpecTree ()] -> IO ()
checkUnusedGoldens = ...
```

This approach will check that for every golden file there is a corresponding node in the spec forest (at least if I'm correctly understanding what `checkUnusedGoldens` is supposed to do).

If on the other hand you want to check that for each golden file a spec item was actually executed (taking `--match` and `--skip` into account), you want something like:

```haskell
hspecAndCheckUnusedGoldens :: Spec -> IO ()
hspecAndCheckUnusedGoldens spec0 = do
  ...
  checkUnusedGoldens (map resultItemPath $ specResultItems result)
  ...

checkUnusedGoldens :: [Path] -> IO ()
checkUnusedGoldens = ...
```

@srid this second scenario is what #656 enables.  But if I understand you correctly, you actually want the first scenario.  Is that correct?  If yes, then I think we would technically not need #656 (even though, it may still be a good idea).

Does this work?

**Comment by sol** [comment]
> More precisely,
> 
> ```haskell
> hspecAndReturnForest spec =
>   hspec spec >> fmap snd (runSpecM spec)
> ```
> 
> Can this function be implemented without evaluating the `spec` twice?

Yes, it can:

```haskell
hspecAndReturnForest :: Spec -> IO [SpecTree ()]
hspecAndReturnForest spec0 = do
  (config, spec) <- evalSpec defaultConfig spec0
  getArgs >>= readConfig config
    >>= withArgs [] . runSpecForest spec
    >>= evaluateSummary -- use evaluateResult instead, if you are on #656
  return spec
```
