### ISSUE TITLE
Ctrl+C interrupting hspec leaves the terminal cursor invisible

### ISSUE THREAD

**Issue by pxeger** [hspec/hspec#678]
1. Run hspec with some tests that enter an infinite loop
2. Press ctrl+c to escape the infinite loop
3. Observe that the terminal cursor is invisible

As a workaround, you can use the command `reset` to get your cursor back, but it would be better if hspec could reset the cursor while cleaning up when it gets interrupted.

**Comment by sol** [comment]
Hspec already takes care of this + I can’t reproduce this issue.

Please provide exact steps to reproduce.

**Comment by sol** [comment]
I will be happy to track this down. However, to do so, I will need exact steps on how to reproduce. I’m closing this for now. If somebody provides exact steps on how to reproduce then I am happy to reopen the issue.
