### ISSUE TITLE
Let specs log trace messages

### ISSUE THREAD

**Issue by plcplc** [hspec/hspec#681]
I'd like to be able to log trace messages from Spec's in a single log file together with logs from hspec Formatters.

Currently there is no good way (that I know of) to do this.

My workaround so far is to:

* Do `s/spec :: Spec/spec :: SpecWith (String -> IO ())/` on the output of `hspec-discover`,
* Have a custom `main` that sets hspec formatters and hands the `String -> IO ()` logging action to specs.

But I think it would be nice to have a cleaner solution for achieving this.

**Comment by sol** [comment]
@plcplc  are you literally running `sed` or something on the `hspec-discover` output? There may not be a perfect solution, but I’m confident that there is a way to achieve what you are trying to do without resorting to `sed`. Recent versions of `hspec-discover` can work with parametric specs. Can you provide a fully self-contained example that captures the gist of what you are doing right now.

**Comment by sol** [comment]
@plcplc I think it’s likely that you can solve your use case with spec hooks. Please take a look at https://hspec.github.io/hspec-discover.html#spec-hooks.

**Comment by plcplc** [comment]
It seems that with the addition of `modifyConfig` I am indeed able to make changes to formatters from within a SpecHook, which lets me integrate logging into both specs and Hspec formatters 👍.
