### ISSUE TITLE
 hard-coded prepositive qualification in the discover utility

### ISSUE THREAD

**Issue by murcake** [hspec/hspec#702]
Enabling -Wprepositive-qualified-module -Werror breaks the discover utility.

It uses prepositive qualified in several places, like [here](https://github.com/hspec/hspec/blob/main/hspec-discover/src/Test/Hspec/Discover/Run.hs#L89) and [here](https://github.com/hspec/hspec/blob/main/hspec-discover/src/Test/Hspec/Discover/Run.hs#L102).

Not sure, how to solve it. A workaroundy way would be to allow specifying this as an -optF argument. A better way would be to deduce this automatically by looking at the list of enabled extensions. I haven't researched this though yet.

If you give me a hint, I can try to fix this.

**Comment by sol** [comment]
I imagine the easiest way to fix this is by changing [this line](https://github.com/hspec/hspec/blob/main/hspec-discover/src/Test/Hspec/Discover/Run.hs#L64) to:

```haskell
  . showString "{-# OPTIONS_GHC -w -Wall -fno-warn-warnings-deprecations #-}\n"
```

We can then also revert https://github.com/hspec/hspec/commit/ffd91356901b2a60bd1f90112b61603348b3df36.

@murcake  please go ahead and try this and open a PR.

**Comment by murcake** [comment]
Makes sense. Is there any reason for keeping the old `-fno-warn-X` syntax instead of `-Wno-X`?

**Comment by sol** [comment]
I guess both work. I think dictionary words are easier to read, but I am OK with both options.

**Comment by murcake** [comment]
> I guess both work. I think dictionary words are easier to read, but I am OK with both options.

It's just that it's [been deprecated](https://downloads.haskell.org/ghc/latest/docs/users_guide/using-warnings.html)

I'll change to `-W-no-X`

**Comment by sol** [comment]
Anything that works and passes CI is fine. You may end up with the `-fno-` form due to old compilers not understanding `-W..`. But CI will point you into the right direction.
