### ISSUE TITLE
Hspec not building on GHC 9.4.2 due to dependency on ghc

### ISSUE THREAD

**Issue by PilchardFriendly** [hspec/hspec#750]
It looks like `hspec-core` has a dependency on ghc, which cannot currently be built (possibly needs Hadrian these days?).
I've tried `ghc-pkg expose  ghc` but to no avail.  

> ghcup list -c set       
   Tool  Version  Tags                 Notes      
✔✔ ghc   9.4.2    latest,base-4.17.0.0 hls-powered
✔✔ cabal 3.8.1.0  latest                          
✔✔ hls   1.8.0.0  latest,recommended              
✔✔ stack 2.9.1    latest,recommended              
✔✔ ghcup 0.1.18.0 latest,recommende
> ghcup debug-info

Debug Info
==========
GHCup base dir: /Users/ndrew/.ghcup
GHCup bin dir: /Users/ndrew/.ghcup/bin
GHCup GHC directory: /Users/ndrew/.ghcup/ghc
GHCup cache directory: /Users/ndrew/.ghcup/cache
Architecture: aarch64
Platform: Darwin
Version: 0.1.18.0

Build Log
========
> cabal test
Resolving dependencies...
Build profile: -w ghc-9.4.2 -O1
In order, the following will be built (use -v for more details):
 - ghc-9.4.2 (lib:ghc) (requires build)
 - quadtree-0.1.0.0 (lib) (first run)
 - hspec-core-2.10.6 (lib) (requires build)
 - hspec-2.10.6 (lib) (requires build)
 - quadtree-0.1.0.0 (test:quadtree-test) (first run)
Configuring library for quadtree-0.1.0.0..
Starting     ghc-9.4.2 (all, legacy fallback)
Preprocessing library for quadtree-0.1.0.0..
Building library for quadtree-0.1.0.0..
[1 of 1] Compiling MyLib            ( src/MyLib.hs, /Users/ndrew/code/sketches/quadtree/dist-newstyle/build/aarch64-osx/ghc-9.4.2/quadtree-0.1.0.0/build/MyLib.o, /Users/ndrew/code/sketches/quadtree/dist-newstyle/build/aarch64-osx/ghc-9.4.2/quadtree-0.1.0.0/build/MyLib.dyn_o )
ld: warning: -undefined dynamic_lookup may not work with chained fixups

Failed to build ghc-9.4.2. The failure occurred during the configure step.
Build log ( /Users/ndrew/.cabal/logs/ghc-9.4.2/ghc-9.4.2-226c55ff.log ):
[1 of 2] Compiling Main             ( /Users/ndrew/code/sketches/quadtree/dist-newstyle/tmp/src-15208/ghc-9.4.2/dist/setup/setup.hs, /Users/ndrew/code/sketches/quadtree/dist-newstyle/tmp/src-15208/ghc-9.4.2/dist/setup/Main.o )
[2 of 2] Linking /Users/ndrew/code/sketches/quadtree/dist-newstyle/tmp/src-15208/ghc-9.4.2/dist/setup/setup
Configuring ghc-9.4.2...
genprimopcode: readCreateProcess: posix_spawnp: does not exist (No such file or directory)
Error: cabal: Failed to build ghc-9.4.2 (which is required by
test:quadtree-test from quadtree-0.1.0.0). See the build log above for
details.

**Comment by sol** [comment]
@PilchardFriendly

**Comment by sol** [comment]
@PilchardFriendly thanks for reporting this. The `ghc` package comes with GHC. It cannot be built from source. The same is true for other packages, most notably `base`.

I am not exactly sure for what reason `cabal` tries to build `ghc` on your system.

@Mikolaj do you have any input on this? Do you know if there are any related Cabal issues?

**Comment by Mikolaj** [comment]
Yes, there are: 
 
https://github.com/haskell/cabal/issues/8554
https://github.com/haskell/cabal/issues/8489

It's cabal's fault if your package (or any of its deps) depends on both ghc and Cabal >= 3.8. Will be fixed in cabal 3.10. For now `--allow-newer`, etc., should help.

**Comment by ysangkok** [comment]
@Mikolaj Are allow-newers also intended to work when upgrading boot packages?

For example, `cabal build hspec-core --constraint='transformers>=0.6'` yields the error

```
[__5] next goal: ghc (dependency of hspec-core)
[__5] rejecting: ghc-9.4.3/installed-9.4.3 (conflict: transformers==0.6.0.4,
ghc => transformers==0.5.6.2/installed-0.5.6.2)
```

So far, so good, that is expected.

But if I add `--allow-newer=transformers,ghci,ghc-boot` to get around this error, it still fails with the same error message. This is unexpected, as I thought I was telling it to ignore any bounds on dependencies for `transformers`.

This is with cabal-install version 3.8.1.0.

**Comment by Mikolaj** [comment]
It complains about `ghc`, but you say `ghc-boot`. These are different packages, I presume?

**Comment by ysangkok** [comment]
@Mikolaj even adding `ghc` and `ghc-heap` gives 

```
 % cabal build hspec-core --constraint='transformers>=0.6' --allow-newer=transformers,ghci,ghc-boot,ghc,ghc-heap 
Resolving dependencies...
Error: cabal: Could not resolve dependencies:
[__0] trying: hspec-2.10.6 (user goal)
[__1] trying: base-4.17.0.0/installed-4.17.0.0 (dependency of hspec)
[__2] trying: QuickCheck-2.14.2 (dependency of hspec)
[__3] next goal: transformers (dependency of QuickCheck)
[__3] rejecting: transformers-0.5.6.2/installed-0.5.6.2 (constraint from
command line flag requires >=0.6)
[__3] trying: transformers-0.6.0.4
[__4] trying: hspec-core-2.10.6 (user goal)
[__5] next goal: ghc (dependency of hspec-core)
[__5] rejecting: ghc-9.4.3/installed-9.4.3 (conflict: transformers==0.6.0.4,
ghc => transformers==0.5.6.2/installed-0.5.6.2)
[__5] trying: ghc-9.4.2
[__6] next goal: ghci (dependency of ghc)
[__6] rejecting: ghci-9.4.3/installed-9.4.3 (conflict: transformers==0.6.0.4,
ghci => transformers==0.5.6.2/installed-0.5.6.2)
[__6] rejecting: ghci-8.10.2 (conflict: ghc => ghci>=9.4.2)
[__6] skipping: ghci-8.10.1, ghci-8.8.3, ghci-8.8.1, ghci-8.6.5, ghci-8.6.4,
ghci-8.6.1, ghci-8.4.4, ghci-8.4.3, ghci-8.4.2, ghci-8.4.1, ghci-8.2.2,
ghci-8.2.1, ghci-8.0.2, ghci-8.0.1 (has the same characteristics that caused
the previous version to fail: excluded by constraint '>=9.4.2' from 'ghc')
[__6] fail (backjumping, conflict set: ghc, ghci, transformers)
After searching the rest of the dependency tree exhaustively, these were the
goals I've had most trouble fulfilling: hspec-core, ghc, ghci, base,
transformers, hspec, QuickCheck
Try running with --minimize-conflict-set to improve the error message.
```

It's this line I don't understand

```
[__6] rejecting: ghci-9.4.3/installed-9.4.3 (conflict: transformers==0.6.0.4,
ghci => transformers==0.5.6.2/installed-0.5.6.2)
```

Why is there a conflict if newer `transformers` are allowed?

**Comment by Mikolaj** [comment]
I think this line means that the package depends on boot non-upgradable package ghci that happens to link against  transformers==0.5.6.2, so you have to use that version of transformers, period. The tickets I linked above may shed some more light on what I wrote or prove it's incorrect altogether. I remember there is an effort (a GHC ticket, I think) to make non-upgradable package upgradable. It may be linked inside the tickets above.

**Comment by sol** [comment]
#755 / `hspec-2.10.7` addresses this.
