### ISSUE TITLE
hspec discover: module `Main` is missing an export list

### ISSUE THREAD

**Issue by keithfancher** [hspec/hspec#790]
When I use the `-Wmissing-export-lists` flag (which is always!) and also use hspec discover, I get the following warning every time I run my tests:

```
kept/test/Spec.hs:1:1: warning: [-Wmissing-export-lists]
    The export item ‘module Main’ is missing an export list
  |         
1 | {-# OPTIONS_GHC -F -pgmF hspec-discover #-}
  | ^       
```

Not a huge deal, but I try to keep a warning-free build so it'd be nice to squash it. Is it possible to add exports to the generated module?

(Not sure if it's naive to think it'd be a quick-ish fix [somewhere around here](https://github.com/hspec/hspec/blob/main/hspec-discover/src/Test/Hspec/Discover/Run.hs#L65).)

**Comment by sol** [comment]
@keithfancher please make sure that you use the latest version of `hspec-discover`. Please report back in case this still doesn't address your issue.

**Comment by keithfancher** [comment]
Thanks for the quick reply! I switched to latest version and it fixed the issue :+1: 

(I was using `2.9.7`, from a Stackage LTS.)

**Comment by bladyjoker** [comment]
Hi,

I'm experiencing the same issue with `2.11.7`

```
❯ which hspec-discover 
/nix/store/y55l3r97if46x2zg0pjhfnpsfa1rykxz-hspec-discover-exe-hspec-discover-2.11.7/bin/hspec-discover
```

Trying to slap a `{-# OPTIONS_GHC -Wno-missing-export-lists #-}` on top of the module doesn't have any effect it seems.

**Comment by sol** [comment]
@bladyjoker this has been fixed in 2.10.3. if there are still issues for you, then I need exact steps to reproduce.

Can you please open a new issue?

**Comment by sol** [comment]
> Trying to slap a `{-# OPTIONS_GHC -Wno-missing-export-lists #-}` on top of the module doesn't have any effect it seems.

Yes, that's not supposed to work. `hspec-discover` does not look at the original source file. The test driver is generated and should compile regardless of what warnings you enable.

**Comment by sol** [comment]
https://github.com/hspec/hspec/commit/c36f006a5cf7b062961ae8e27a51cc7c7594af78

**Comment by bladyjoker** [comment]
Thanks @sol, I'll make a reproducible example or if I realize my mistake in the mean time I'll report back here what the problem was.
