### ISSUE TITLE
How can I get the "it" description?

### ISSUE THREAD

**Issue by CristhianMotoche** [hspec/hspec#855]
I see there is a way to get the list of descriptions from every parent describe using [`getSpecDescriptionPath`](https://hackage.haskell.org/package/hspec-core-2.11.4/docs/Test-Hspec-Core-Spec.html#v:getSpecDescriptionPath). Is there something similar to get the description of the current test? For example:

```hs
describe "foo" $
  describe "bar" $
    it "does something" $ do
      itDescription <- getItDescription
      itDescription == "does something"
```

**Comment by sol** [comment]
I think that wouldn't type check, but see https://github.com/stackbuilders/hspec-golden/issues/43#issuecomment-1704058107.
