### ISSUE TITLE
Use displayException instead of show

### ISSUE THREAD

**Issue by pbrisbin** [hspec/hspec#856]
I'm opening a new issue for #289 as suggested, I'd like lobby for such a change.

My understanding is that `Show` should not be (ab)used to make values prettier for human eyes. It should always output parse-able Haskell, round-trip with `Read` and (for these reasons), deriving it is best. Other type-classes should be used for improving values for human eyes, and `Exception(displayException)` is exactly this for exceptions. I wish I had a source for this, but I can't remember where I read it, I just know that I've internalized it.

A derived, "must parse as Haskell" `Show` instance is _god-awful_ to read for large and complex error types. We have large test-suites with some dense exception types, and when they fail through hspec they take ages to "parse", with my eyes. However, the ones I work on have very, very nice `displayException` implementations that we use for Bugsnag and logging. It doesn't hide any debugging information, it just makes it easier to consume as a human. I would very much prefer this in hspec, and I'd prefer to not abuse `show` to accomplish it.

IMO, if you've defined a `displayException` that doesn't provide "all available information" such that the original error can be debugged, that's a bug in your `displayException` -- and hspec using it would actually help you find/solve that bug. In most cases `displayException = show` so nothing is changed, but if you've gone to the trouble to make "displaying an exception" better, it'd be nice if tools that "displayed an exception", such as hspec, utilized it.

**Comment by sol** [comment]
When I get an unexpected exception, this are the things that I'm most interested in:
1. Where did the exception occur?
2. What is the type of the exception? How can I catch it?

Things got somewhat better in the last couple of years, but at times it's still not trivial to answer those questions.

The best thing we have is to rely on (derived) `Show` instances, except for that exceptions from `base` don't derive `Show`, leaving you with something like:
```
fd:12: commitBuffer: resource vanished (Broken pipe)
```

What's the type of that exception? How can you catch it?

As an experienced Haskell programmer you know. But you have to know this things.  There's no easy way to discover this information from the error message.

This gets even worse when the exception is coming from some third-party dependency.

So far, my mantra here was:

1. Avoid throwing exceptions in the first place
2. Always derive `Show` for custom exception types

And specifically for Hspec:

3. Use `show` when showing exceptions to the user

However:

- For `base` exceptions it doesn't really matter what we do here, `Show` instances are not derived and `displayException` is the same as `show`.
- Hspec already jumps through some hoops to give the user as much typing information as possible.
- For third-party exceptions I probably would prefer `show`.
- For in-house exceptions I might prefer `displayException`, or I might even want to customize how exactly they are rendered.


So here is the proposal :
- add a `configFormatException :: SomeException -> String` field to `Config` and use that when showing exceptions
- add a `--show-exceptions` flag that sets `configFormatException` to `show`
- add a `--display-exceptions` flag that sets `configFormatException` to `displayException`

How about this?

**Comment by pbrisbin** [comment]
Thank you for the careful thought and laying out the landscape as you understood it.

> How about this?

Absolutely love it.
