### ISSUE TITLE
with fail-fast the cleanup action of aroundAllWith is not executed

### ISSUE THREAD

**Issue by mklinik** [hspec/hspec#860]
I'm running my test suite with `--fail-fast`. When there are multiple spec items in an `aroundAllWith` block, and the first one fails, the cleanup action of the hook is not executed.

- it works with `aroundWith`
- it works when the failing test is the last (or the only) in the block
- it works when running without `--fail-fast`

The following is a minimal example that produces the issue.

* Expected outcome: both "initialize" and "teardown" are printed.
* Actual outcome: only "initialize" is printed.

```
module Main (main) where

import Test.Hspec
import Control.Exception

spec :: Spec
spec =
  aroundAllWith myHook $ do
    it "foos" $
      True `shouldBe` False
    it "bars" $
      True `shouldBe` True

main :: IO ()
main = hspec spec

myHook :: (ActionWith () -> ActionWith ())
myHook unitTests state =
  bracket_
    (putStrLn "initialize")
    (putStrLn "teardown")
    (unitTests state)

```

**Comment by sol** [comment]
I think this is the code to blame: https://github.com/hspec/hspec/blob/5d24282716b8dd5dc7c92be0f31ca5de870dd985/hspec-core/src/Test/Hspec/Core/Runner/Eval.hs#L187-L193

This code eliminates the cleanup action by combining it with the last node.

I think this needs to be changed in the following way:
- When fail-fast then for every child node, check the result + run the cleanup on failure
- Unconditionally run the clean up one the last node

So I think this can be addressed locally here in this function. It still feels a little bit hacky, not sure if there's a better way.

**Comment by sol** [comment]
BTW, I think this can be reproduced with a more minimal example that only uses `atferAll_`.
