### ISSUE TITLE
`x-partial` warning with GHC 9.8

### ISSUE THREAD

**Issue by andreasabel** [hspec/hspec#861]
```
vendor/Data/Algorithm/Diff.hs:74:23: warning: [GHC-63394] [-Wx-partial]
    In the use of ‘head’
    (imported from Prelude, but defined in GHC.List):
    "This is a partial function, it throws an error on empty lists. Use pattern matching or Data.List.uncons instead. Consider refactoring to use Data.List.NonEmpty."
   |
74 | lcs eq as bs = path . head . dropWhile (\dl -> poi dl /= lena || poj dl /= lenb) .
   |                       ^^^^
```
Code: https://github.com/hspec/hspec/blob/5d24282716b8dd5dc7c92be0f31ca5de870dd985/hspec-core/vendor/Data/Algorithm/Diff.hs#L73-L78
It is not apparent that this use of `head` is safe, but a closer look might justify it.

NB: maybe `dstep` should return return a non-empty list. https://github.com/hspec/hspec/blob/5d24282716b8dd5dc7c92be0f31ca5de870dd985/hspec-core/vendor/Data/Algorithm/Diff.hs#L54-L64

**Comment by sol** [comment]
https://github.com/hspec/hspec/pull/864
