### ISSUE TITLE
How to verify a predicate against each element of a list?

### ISSUE THREAD

**Issue by asarkar** [hspec/hspec#876]
How would you verify a predicate against each element of a resulting list? For example, if `xs ~ [Int]`, and `ys` is the result from function that multiplies each element of `xs` by `2`, you want to check each element has indeed been doubled. If you run some sort of `(all . map/zip)` whatever, you end up with a message "expected: True but got: False", which is completely useless. You need to know which exact element failed.

Disclaimer: Initially reported on [hspec-expectations](https://github.com/hspec/hspec-expectations/issues/68). Not sure which group would be the best to handle it, will close one of the tickets if any one of the groups take ownership.

**Comment by sol** [comment]
That's a problem I never really had and that I never thought about, so I'm not in a good position to offer advice.

The first thing I would do is to come up with an interface that I, as a  programmer, would want to use to specify my expectation.

After that, it's probably easy to implement combinators that provide that interface.

**Comment by asarkar** [comment]
@sol IMO, this is a _very_ common ask. For example, in the JVM world, there's AssertJ, using which you can write combinators such as:
```
assertThat(fellowshipOfTheRing)
  .hasSize(9)
  .contains(frodo, sam)
  .doesNotContain(sauron);
```
I tried using `forM`, turning `[a]` to `[Expectation]`, but the test expects a single `Expectation` to be returned, and I couldn't find a way to combine them.

**Comment by sol** [comment]
> this is a _very_ common ask

I'm really not sure. I assume your example is contrived. Possibly you want to do property testing,  not sure.

> For example, in the JVM world, there's AssertJ, using which you can write combinators such as:
> 
> ```
> assertThat(fellowshipOfTheRing)
>   .hasSize(9)
>   .contains(frodo, sam)
>   .doesNotContain(sauron);
> ```

I think you can set those expectations with Hspec, essentially achieving the same, no?

> I tried using `forM`

You may want to use `forM_` instead.

> turning `[a]` to `[Expectation]`, but the test expects a single `Expectation` to be returned, and I couldn't find a way to combine them.

you could do that with `sequence_`, but you probably don't need this.

**Comment by asarkar** [comment]
> You may want to use `forM_` instead 

but `forM_` will discard the expectations. So, if one element in the list failed, wouldn’t that expectation be didcarded? I looked for a Semigroup/monoid instance for ‘Expectation`, didn’t find one. But it seems to be a monad, so, there’s probably a way to combine the results.

**Comment by sol** [comment]
> I looked for a Semigroup/monoid instance for `Expectation`, didn’t find one. But it seems to be a monad, so, there’s probably a way to combine the results.

@asarkar sorry for the late reply. You can use `sequence` (or by extension `forM_`, `mapM_`, or do-notation).

```haskell
length fellowshipOfTheRing `shouldBe` 9
fellowshipOfTheRing `shouldContain` frodo
fellowshipOfTheRing `shouldContain` sam
fellowshipOfTheRing `shouldNotContain` sauron
forM_ fellowshipOfTheRing $ \ member -> do
  member.allegiance `shouldBe` Good
```
