### ISSUE TITLE
hspec-discover: builderMainLoop: exec: invalid argument (Bad file descriptor)

### ISSUE THREAD

**Issue by BebeSparkelSparkel** [hspec/hspec#879]
I am transitioning a stack  package to a cabal project and now my tests will not run with the following

```txt
$ cabal test -O0                            
Build profile: -w ghc-9.2.7 -O0
In order, the following will be built (use -v for more details):
 - biparsing-0.0.0.1 (test:spec) (first run)
Preprocessing test suite 'spec' for biparsing-0.0.0.1..
Building test suite 'spec' for biparsing-0.0.0.1..

tests/Spec.hs:1:1: error:
    hspec-discover: builderMainLoop: exec: invalid argument (Bad file descriptor)
  |
1 | {-# OPTIONS_GHC -Wno-prepositive-qualified-module #-}
  | ^
```

this used to work with `stack test --fast`. Is there a way to fix this?

 https://github.com/BebeSparkelSparkel/biparsing/blob/master/biparsing/tests/Spec.hs

**Comment by BebeSparkelSparkel** [comment]
`cabal install hspec-discover` temporarily fixes this but is not ideal.

**Comment by sol** [comment]
https://github.com/sol/simdutf-haskell/blob/389a0b944fb21b987301985818bbfe17d4cd897b/package.yaml#L33

Add this to your `package.yaml` and make sure regenerate your `.cabal` file by running `hpack`.

**Comment by sol** [comment]
You may also decide to open a bug for `haskell/cabal`, if only for the cryptic error message.

**Comment by BebeSparkelSparkel** [comment]
@sol Thanks for the help. I created the ghc issue  https://gitlab.haskell.org/ghc/ghc/-/issues/24581
