### ISSUE TITLE
Question: Using a custom monads for tests in combination with hooks

### ISSUE THREAD

**Issue by soenkehahn** [hspec/hspec#888]
It's possible to write tests in a custom monad stack by implementing an instance for `Example`.

It's also possible then to still use hooks (e.g. `around_`).

But the hooks all work on values of type `IO ()`. Is it somehow possible to get access to the custom monad in the hooks?

More concretely I would like to do something like this:

```haskell
type M a = ReaderT Int IO a

setupTest :: M a -> M a
setupTest = local (const 42)

spec :: Spec
spec = around_ setupTest $ do
  it "a" $ do
    n <- ask
    -- should be 42
    liftIO $ print n

  it "b" $ do
    n <- ask
    -- still 42
    liftIO $ print n
```

I hope the example conveys the general idea, please let me know, if not!

**Comment by sol** [comment]
> Is it somehow possible to get access to the custom monad in the hooks?

Yes, you can define a custom version of `around_` to make this work:

```haskell
around_ :: (M () -> M ()) -> SpecWith Int -> SpecWith Int
around_ action = do
  aroundWith $ \ (item :: Int -> IO ()) -> do
    runReaderT $ do
      action (ReaderT item)
```

Basically, what's happening here is:

1. The `Example` instance for `M` unwraps the custom monad stack
2. For that reason, in the hook you have to wrap it again, so that you can pass it to `M () -> M ()`, then after that unwrap the result again.

Full example:
```haskell
{-# LANGUAGE TypeFamilies #-}
module RunSpec (spec) where

import Test.Hspec hiding (around_)
import Test.Hspec.Core.Spec

import Control.Monad.IO.Class
import Control.Monad.Trans.Reader

type M a = ReaderT Int IO a

instance Example (M ()) where
  type Arg (M ()) = Int
  evaluateExample item params hook = evaluateExample (hook $ runReaderT item) params ($ ())

setupTest :: M a -> M a
setupTest = local (const 42)

around_ :: (M () -> M ()) -> SpecWith Int -> SpecWith Int
around_ action = do
  aroundWith $ \ (item :: Int -> IO ()) -> do
    runReaderT $ do
      action (ReaderT item)

spec :: Spec
spec = before (return 22) $ do
  around_ setupTest $ do
    it "a" $ do
      n <- ask :: M Int
      liftIO $ n `shouldBe` 42

    it "b" $ do
      n <- ask :: M Int
      liftIO $ n `shouldBe` 42
```
It would be nice to generalize this over say `MonadUnliftIO`, but I don't think that's possible.

**Comment by soenkehahn** [comment]
Nice, this worked well for our custom monad. Thanks a lot for the detailed reply.

Our monad stack also contained an `ExceptT` layer, so we're throwing a custom `Exception` in the `Example` instance. And in our version of `around_` we have to take care to catch and re-throw that custom exception in the right places, to allow the wrappers to catch monadic errors.

Also, our monad stack contained *two* `ReaderT`s (one wrapped in a `LoggingT` newtype wrapper), so we had to put both reader states into `SpecWith` (i.e. `SpecWith (LoggingTValue, ReaderTValue)`).

So it was a bit more complicated, but it works. :)

> It would be nice to generalize this over say `MonadUnliftIO`, but I don't think that's possible.

I also don't think so. For generalizing this we would need a way to compute the type to pass to `SpecWith` from a monad stack. So we'd need something like `MonadReaderContext` so that we could do `SpecWith (MonadReaderContext MyCustomMonad)`. Where `MonadReaderContext (ReaderT Int IO) ~ Int`, but we would also need e.g. `MonadReaderContext (ReaderT Int (ReaderT String IO))` to evaluate to something like `(Int, String)`. I don't know of any typeclass that does that. (And that's not even taking into account things like `ExceptT` and `StateT`.)

I'll close this as being solved.
