### ISSUE TITLE
Is hspec-discover in build-tools required?

### ISSUE THREAD

**Issue by pbrisbin** [hspec/hspec#905]
Hi there-

I received a contribution on one of my projects [adding `hspec-discover` to `build-tools`](https://github.com/pbrisbin/hs-shellwords/pull/12) in `package.yaml`. The contributor said `cabal test` fails without it. I use `stack`, and it works fine for me.

It's a minor, not-harmful change, and I could probably just merge it, but the more I look into this, the more confused I get, so I'm wondering if you can help clear things up. Nothing about `build-tools` is not mentioned in the [docs](https://hspec.github.io/hspec-discover.html), so maybe I can contribute something there once I understand better.

Going by `hspec-example`, I do see `build-tool-depends` [in the `.cabal` file](https://github.com/hspec/hspec-example/blob/95db08c7e9a166e62ba630bce58c29a2e661811d/strip.cabal#L42), which I assume is what is actually needed to get my user's `cabal test` working, but that's not mentioned in `hspec-example`'s `package.yaml`.

I do see `package.yaml` using this `defaults` key pointing to `hspec/hspec@main` (TIL!), but [_that_ `package.yaml`](https://github.com/hspec/hspec/blob/main/package.yaml) also doesn't say anything about `build-tools`.

So, can you help clear some things up?

1. Is `build-tools` or `build-tools-depends` needed in `.cabal` for `hspec-discover` to work with `cabal test`?
2. If so, how did it get into the `hspec-example`'s `.cabal` file?

**Comment by sol** [comment]
> The contributor said `cabal test` fails without it. I use `stack`, and it works fine for me.

This is a breaking change that `cabal` introduced at some point.  `stack` chose not to replicate this breaking change. This is why it works with `stack`, but not with `cabal`.

> 1. Is `build-tools` or `build-tools-depends` needed in `.cabal` for `hspec-discover` to work with `cabal test`?

Yes, it's needed for `cabal`.

> 2. If so, how did it get into the `hspec-example`'s `.cabal` file?

From https://github.com/hspec/hspec/blob/main/.hpack/defaults.yaml.

See the corresponding documentation for `defaults`: https://github.com/sol/hpack?tab=readme-ov-file#defaults

**Comment by sol** [comment]
Updates to the documentation very much  welcome!
